#ifndef GUARD_CONSTANTS_FLAGS_JOHTO_H
#define GUARD_CONSTANTS_FLAGS_JOHTO_H

// Johto flags (0x1000-0x10EF)
#define JOHTO_FLAGS_START  0x1000

#ifndef FLAG_AMPHAROS_HEALED
#define FLAG_AMPHAROS_HEALED  0x1000
#endif
#ifndef FLAG_DAY_POKEMON
#define FLAG_DAY_POKEMON  0x1001
#endif
#ifndef FLAG_DELIVERED_EGG
#define FLAG_DELIVERED_EGG  0x1002
#endif
#ifndef FLAG_ENABLE_BAOBA_MATCH_CALL
#define FLAG_ENABLE_BAOBA_MATCH_CALL  0x1003
#endif
#ifndef FLAG_ENABLE_RADIO
#define FLAG_ENABLE_RADIO  0x1004
#endif
#ifndef FLAG_HIDE_AZALEA_ARIADOS_LEFT
#define FLAG_HIDE_AZALEA_ARIADOS_LEFT  0x1005
#endif
#ifndef FLAG_HIDE_AZALEA_ARIADOS_MID
#define FLAG_HIDE_AZALEA_ARIADOS_MID  0x1006
#endif
#ifndef FLAG_HIDE_AZALEA_ARIADOS_RIGHT
#define FLAG_HIDE_AZALEA_ARIADOS_RIGHT  0x1007
#endif
#ifndef FLAG_HIDE_AZALEA_TOWN_CUT_MASTER
#define FLAG_HIDE_AZALEA_TOWN_CUT_MASTER  0x1008
#endif
#ifndef FLAG_HIDE_AZALEA_TOWN_FARFETCHD
#define FLAG_HIDE_AZALEA_TOWN_FARFETCHD  0x1009
#endif
#ifndef FLAG_HIDE_AZALEA_TOWN_KURT
#define FLAG_HIDE_AZALEA_TOWN_KURT  0x100A
#endif
#ifndef FLAG_HIDE_AZALEA_TOWN_ROCKETS
#define FLAG_HIDE_AZALEA_TOWN_ROCKETS  0x100B
#endif
#ifndef FLAG_HIDE_AZALEA_TOWN_SILVER
#define FLAG_HIDE_AZALEA_TOWN_SILVER  0x100C
#endif
#ifndef FLAG_HIDE_AZALEA_TOWN_SLOWPOKE
#define FLAG_HIDE_AZALEA_TOWN_SLOWPOKE  0x100D
#endif
#ifndef FLAG_HIDE_AZALEA_TOWN_WELL_ROCKET
#define FLAG_HIDE_AZALEA_TOWN_WELL_ROCKET  0x100E
#endif
#ifndef FLAG_HIDE_BELLCHIME_MORTY
#define FLAG_HIDE_BELLCHIME_MORTY  0x100F
#endif
#ifndef FLAG_HIDE_BUG_CONTEST_ATTENDANT_SIDE
#define FLAG_HIDE_BUG_CONTEST_ATTENDANT_SIDE  0x1010
#endif
#ifndef FLAG_HIDE_BURNED_TOWER_B1F_EUSINE
#define FLAG_HIDE_BURNED_TOWER_B1F_EUSINE  0x1011
#endif
#ifndef FLAG_HIDE_BURNED_TOWER_BEASTS
#define FLAG_HIDE_BURNED_TOWER_BEASTS  0x1012
#endif
#ifndef FLAG_HIDE_BURNED_TOWER_NPCS
#define FLAG_HIDE_BURNED_TOWER_NPCS  0x1013
#endif
#ifndef FLAG_HIDE_CAFE_JASMINE
#define FLAG_HIDE_CAFE_JASMINE  0x1014
#endif
#ifndef FLAG_HIDE_CHERRYGROVE_GUIDE_GENT_HOUSE
#define FLAG_HIDE_CHERRYGROVE_GUIDE_GENT_HOUSE  0x1015
#endif
#ifndef FLAG_HIDE_CHIKORITABALL
#define FLAG_HIDE_CHIKORITABALL  0x1016
#endif
#ifndef FLAG_HIDE_CIANWOOD_EUSINE
#define FLAG_HIDE_CIANWOOD_EUSINE  0x1017
#endif
#ifndef FLAG_HIDE_CIANWOOD_SUICUNE
#define FLAG_HIDE_CIANWOOD_SUICUNE  0x1018
#endif
#ifndef FLAG_HIDE_CYNDAQUILBALL
#define FLAG_HIDE_CYNDAQUILBALL  0x1019
#endif
#ifndef FLAG_HIDE_DEN_CLAIR
#define FLAG_HIDE_DEN_CLAIR  0x101A
#endif
#ifndef FLAG_HIDE_DEPTSTORE_WHITNEY
#define FLAG_HIDE_DEPTSTORE_WHITNEY  0x101B
#endif
#ifndef FLAG_HIDE_DRAGONS_DEN_CAVERN_CLAIR
#define FLAG_HIDE_DRAGONS_DEN_CAVERN_CLAIR  0x101C
#endif
#ifndef FLAG_HIDE_DRAGONS_DEN_CAVERN_LANCE
#define FLAG_HIDE_DRAGONS_DEN_CAVERN_LANCE  0x101D
#endif
#ifndef FLAG_HIDE_DRAGONS_DEN_CAVERN_SILVER
#define FLAG_HIDE_DRAGONS_DEN_CAVERN_SILVER  0x101E
#endif
#ifndef FLAG_HIDE_DRAGONS_DEN_SHRINE_CLAIR
#define FLAG_HIDE_DRAGONS_DEN_SHRINE_CLAIR  0x101F
#endif
#ifndef FLAG_HIDE_ECRUTEAK_BILL
#define FLAG_HIDE_ECRUTEAK_BILL  0x1020
#endif
#ifndef FLAG_HIDE_ECRUTEAK_CITY_SAGE
#define FLAG_HIDE_ECRUTEAK_CITY_SAGE  0x1021
#endif
#ifndef FLAG_HIDE_ECRUTEAK_CITY_THEATER_KIMONOS
#define FLAG_HIDE_ECRUTEAK_CITY_THEATER_KIMONOS  0x1022
#endif
#ifndef FLAG_HIDE_ECRUTEAK_CITY_THEATER_NPCS
#define FLAG_HIDE_ECRUTEAK_CITY_THEATER_NPCS  0x1023
#endif
#ifndef FLAG_HIDE_ECRUTEAK_CITY_THEATER_ZUKI
#define FLAG_HIDE_ECRUTEAK_CITY_THEATER_ZUKI  0x1024
#endif
#ifndef FLAG_HIDE_ECRUTEAK_ROCKET
#define FLAG_HIDE_ECRUTEAK_ROCKET  0x1025
#endif
#ifndef FLAG_HIDE_ECRUTEAK_SILVER
#define FLAG_HIDE_ECRUTEAK_SILVER  0x1026
#endif
#ifndef FLAG_HIDE_GOLDENROD_BEAUTY
#define FLAG_HIDE_GOLDENROD_BEAUTY  0x1027
#endif
#ifndef FLAG_HIDE_GOLDENROD_BILL
#define FLAG_HIDE_GOLDENROD_BILL  0x1028
#endif
#ifndef FLAG_HIDE_GOLDENROD_NPCS
#define FLAG_HIDE_GOLDENROD_NPCS  0x1029
#endif
#ifndef FLAG_HIDE_GOLDENROD_RADIOTOWER_DIRECTOR
#define FLAG_HIDE_GOLDENROD_RADIOTOWER_DIRECTOR  0x102A
#endif
#ifndef FLAG_HIDE_GOLDENROD_RADIOTOWER_DIRECTOR_2
#define FLAG_HIDE_GOLDENROD_RADIOTOWER_DIRECTOR_2  0x102B
#endif
#ifndef FLAG_HIDE_GOLDENROD_RADIOTOWER_PETREL
#define FLAG_HIDE_GOLDENROD_RADIOTOWER_PETREL  0x102C
#endif
#ifndef FLAG_HIDE_GOLDENROD_ROCKET_SCOUT
#define FLAG_HIDE_GOLDENROD_ROCKET_SCOUT  0x102D
#endif
#ifndef FLAG_HIDE_GOLDENROD_ROCKETS
#define FLAG_HIDE_GOLDENROD_ROCKETS  0x102E
#endif
#ifndef FLAG_HIDE_GOLDENROD_UNDERGROUND_KIMONO
#define FLAG_HIDE_GOLDENROD_UNDERGROUND_KIMONO  0x102F
#endif
#ifndef FLAG_HIDE_GOLDENROD_UNDERGROUND_SILVER
#define FLAG_HIDE_GOLDENROD_UNDERGROUND_SILVER  0x1030
#endif
#ifndef FLAG_HIDE_GUIDE_GENT_CHERRYGROVE
#define FLAG_HIDE_GUIDE_GENT_CHERRYGROVE  0x1031
#endif
#ifndef FLAG_HIDE_ICE_PATH_KIMONO
#define FLAG_HIDE_ICE_PATH_KIMONO  0x1032
#endif
#ifndef FLAG_HIDE_JOHTO_GYM_LEADERS
#define FLAG_HIDE_JOHTO_GYM_LEADERS  0x1033
#endif
#ifndef FLAG_HIDE_KURT_1
#define FLAG_HIDE_KURT_1  0x1034
#endif
#ifndef FLAG_HIDE_KURT_2
#define FLAG_HIDE_KURT_2  0x1035
#endif
#ifndef FLAG_HIDE_LAB_POLICEMAN
#define FLAG_HIDE_LAB_POLICEMAN  0x1036
#endif
#ifndef FLAG_HIDE_LAKE_OF_RAGE_GYARADOS
#define FLAG_HIDE_LAKE_OF_RAGE_GYARADOS  0x1037
#endif
#ifndef FLAG_HIDE_LAKE_OF_RAGE_LANCE
#define FLAG_HIDE_LAKE_OF_RAGE_LANCE  0x1038
#endif
#ifndef FLAG_HIDE_LAKE_PRYCE
#define FLAG_HIDE_LAKE_PRYCE  0x1039
#endif
#ifndef FLAG_HIDE_LIGHTHOUSE_JASMINE
#define FLAG_HIDE_LIGHTHOUSE_JASMINE  0x103A
#endif
#ifndef FLAG_HIDE_MAHOGANY_TOWN_FATMAN
#define FLAG_HIDE_MAHOGANY_TOWN_FATMAN  0x103B
#endif
#ifndef FLAG_HIDE_MAHOGANY_TOWN_SHOP_NPCS
#define FLAG_HIDE_MAHOGANY_TOWN_SHOP_NPCS  0x103C
#endif
#ifndef FLAG_HIDE_MOMS_FRIEND
#define FLAG_HIDE_MOMS_FRIEND  0x103D
#endif
#ifndef FLAG_HIDE_MOMS_FRIEND2
#define FLAG_HIDE_MOMS_FRIEND2  0x103E
#endif
#ifndef FLAG_HIDE_MRPOKEMON
#define FLAG_HIDE_MRPOKEMON  0x103F
#endif
#ifndef FLAG_HIDE_MTSILVER_RED
#define FLAG_HIDE_MTSILVER_RED  0x1040
#endif
#ifndef FLAG_HIDE_NEWBARKTOWN_LAB_AIDE
#define FLAG_HIDE_NEWBARKTOWN_LAB_AIDE  0x1041
#endif
#ifndef FLAG_HIDE_OLIVINE_CITY_GYM_JASMINE
#define FLAG_HIDE_OLIVINE_CITY_GYM_JASMINE  0x1042
#endif
#ifndef FLAG_HIDE_OLIVINE_PORT_OAK
#define FLAG_HIDE_OLIVINE_PORT_OAK  0x1043
#endif
#ifndef FLAG_HIDE_OLIVINE_SABRINA
#define FLAG_HIDE_OLIVINE_SABRINA  0x1044
#endif
#ifndef FLAG_HIDE_OLIVINE_SILVER
#define FLAG_HIDE_OLIVINE_SILVER  0x1045
#endif
#ifndef FLAG_HIDE_RAYQUAZA
#define FLAG_HIDE_RAYQUAZA  0x1046
#endif
#ifndef FLAG_HIDE_ROCKET_GOLDENROD_RADIOTOWER_1
#define FLAG_HIDE_ROCKET_GOLDENROD_RADIOTOWER_1  0x1047
#endif
#ifndef FLAG_HIDE_ROUTE_30_NPCS
#define FLAG_HIDE_ROUTE_30_NPCS  0x1048
#endif
#ifndef FLAG_HIDE_ROUTE39_SHADOW
#define FLAG_HIDE_ROUTE39_SHADOW  0x1049
#endif
#ifndef FLAG_HIDE_SILVER_CHERRYGROVE
#define FLAG_HIDE_SILVER_CHERRYGROVE  0x104A
#endif
#ifndef FLAG_HIDE_SILVER_NEWBARKTOWN
#define FLAG_HIDE_SILVER_NEWBARKTOWN  0x104B
#endif
#ifndef FLAG_HIDE_SLOWPOKE_WELL_KURT
#define FLAG_HIDE_SLOWPOKE_WELL_KURT  0x104C
#endif
#ifndef FLAG_HIDE_SPROUT_TOWER_SILVER
#define FLAG_HIDE_SPROUT_TOWER_SILVER  0x104D
#endif
#ifndef FLAG_HIDE_SUDOWOODO
#define FLAG_HIDE_SUDOWOODO  0x104E
#endif
#ifndef FLAG_HIDE_TOTODILEBALL
#define FLAG_HIDE_TOTODILEBALL  0x104F
#endif
#ifndef FLAG_HIDE_TRAINER_SCHOOL_EARL
#define FLAG_HIDE_TRAINER_SCHOOL_EARL  0x1050
#endif
#ifndef FLAG_HIDE_UNION_CAVE_LAPRAS
#define FLAG_HIDE_UNION_CAVE_LAPRAS  0x1051
#endif
#ifndef FLAG_HIDE_VIOLET_CITY_AIDE
#define FLAG_HIDE_VIOLET_CITY_AIDE  0x1052
#endif
#ifndef FLAG_HIDE_VIOLET_CITY_EARL
#define FLAG_HIDE_VIOLET_CITY_EARL  0x1053
#endif
#ifndef FLAG_HIDE_VIOLET_CITY_KIMONO_GIRL
#define FLAG_HIDE_VIOLET_CITY_KIMONO_GIRL  0x1054
#endif
#ifndef FLAG_HIDE_WHIRL_ISLANDS_KIMONO_GIRLS
#define FLAG_HIDE_WHIRL_ISLANDS_KIMONO_GIRLS  0x1055
#endif
#ifndef FLAG_HIDE_WHIRL_ISLANDS_TENTACRUEL
#define FLAG_HIDE_WHIRL_ISLANDS_TENTACRUEL  0x1056
#endif
#ifndef FLAG_ITEM_BELLCHIME_BIG_MUSHROOM
#define FLAG_ITEM_BELLCHIME_BIG_MUSHROOM  0x1057
#endif
#ifndef FLAG_ITEM_BURNED_TOWER_1F_ETHER
#define FLAG_ITEM_BURNED_TOWER_1F_ETHER  0x1058
#endif
#ifndef FLAG_ITEM_BURNED_TOWER_1F_HP_UP
#define FLAG_ITEM_BURNED_TOWER_1F_HP_UP  0x1059
#endif
#ifndef FLAG_ITEM_BURNED_TOWER_B1F_TM_TAUNT
#define FLAG_ITEM_BURNED_TOWER_B1F_TM_TAUNT  0x105A
#endif
#ifndef FLAG_ITEM_BURNED_TOWER_B1F_ULTRA_BALL
#define FLAG_ITEM_BURNED_TOWER_B1F_ULTRA_BALL  0x105B
#endif
#ifndef FLAG_ITEM_DARKCAVE1_ELIXIR
#define FLAG_ITEM_DARKCAVE1_ELIXIR  0x105C
#endif
#ifndef FLAG_ITEM_DARKCAVE1_MAX_REVIVE
#define FLAG_ITEM_DARKCAVE1_MAX_REVIVE  0x105D
#endif
#ifndef FLAG_ITEM_DARKCAVE1_POTION
#define FLAG_ITEM_DARKCAVE1_POTION  0x105E
#endif
#ifndef FLAG_ITEM_DARKCAVE1_REVIVE
#define FLAG_ITEM_DARKCAVE1_REVIVE  0x105F
#endif
#ifndef FLAG_ITEM_DARKCAVE2_BLACK_FLUTE
#define FLAG_ITEM_DARKCAVE2_BLACK_FLUTE  0x1060
#endif
#ifndef FLAG_ITEM_DARKCAVE2_STAR_PIECE
#define FLAG_ITEM_DARKCAVE2_STAR_PIECE  0x1061
#endif
#ifndef FLAG_ITEM_DOME_FOSSIL
#define FLAG_ITEM_DOME_FOSSIL  0x1062
#endif
#ifndef FLAG_ITEM_DRAGONSDEN2_DRAGON_FANG
#define FLAG_ITEM_DRAGONSDEN2_DRAGON_FANG  0x1063
#endif
#ifndef FLAG_ITEM_DRAGONSDEN2_MAX_POTION
#define FLAG_ITEM_DRAGONSDEN2_MAX_POTION  0x1064
#endif
#ifndef FLAG_ITEM_DRAGONSDEN2_PP_MAX
#define FLAG_ITEM_DRAGONSDEN2_PP_MAX  0x1065
#endif
#ifndef FLAG_ITEM_ECRUTEAK_RARE_CANDY
#define FLAG_ITEM_ECRUTEAK_RARE_CANDY  0x1066
#endif
#ifndef FLAG_ITEM_GOLDENROD_UNDERGROUND_AMULET_COIN
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_AMULET_COIN  0x1067
#endif
#ifndef FLAG_ITEM_GOLDENROD_UNDERGROUND_ANTIDOTE
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_ANTIDOTE  0x1068
#endif
#ifndef FLAG_ITEM_GOLDENROD_UNDERGROUND_COIN_CASE
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_COIN_CASE  0x1069
#endif
#ifndef FLAG_ITEM_GOLDENROD_UNDERGROUND_ETHER
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_ETHER  0x106A
#endif
#ifndef FLAG_ITEM_GOLDENROD_UNDERGROUND_EXP_SHARE
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_EXP_SHARE  0x106B
#endif
#ifndef FLAG_ITEM_GOLDENROD_UNDERGROUND_MAX_ETHER
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_MAX_ETHER  0x106C
#endif
#ifndef FLAG_ITEM_GOLDENROD_UNDERGROUND_MAX_POTION
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_MAX_POTION  0x106D
#endif
#ifndef FLAG_ITEM_GOLDENROD_UNDERGROUND_PARALYZE_HEAL
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_PARALYZE_HEAL  0x106E
#endif
#ifndef FLAG_ITEM_GOLDENROD_UNDERGROUND_REVIVE
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_REVIVE  0x106F
#endif
#ifndef FLAG_ITEM_GOLDENROD_UNDERGROUND_SMOKE_BALL
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_SMOKE_BALL  0x1070
#endif
#ifndef FLAG_ITEM_GOLDENROD_UNDERGROUND_SUPER_POTION
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_SUPER_POTION  0x1071
#endif
#ifndef FLAG_ITEM_GOLDENROD_UNDERGROUND_TM_CALM_MIND
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_TM_CALM_MIND  0x1072
#endif
#ifndef FLAG_ITEM_GOLDENROD_UNDERGROUND_ULTRA_BALL
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_ULTRA_BALL  0x1073
#endif
#ifndef FLAG_ITEM_GOLDENROD_UNDERGROUND_ULTRA_BALL2
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_ULTRA_BALL2  0x1074
#endif
#ifndef FLAG_ITEM_GS_BALL
#define FLAG_ITEM_GS_BALL  0x1075
#endif
#ifndef FLAG_ITEM_HELIX_FOSSIL
#define FLAG_ITEM_HELIX_FOSSIL  0x1076
#endif
#ifndef FLAG_ITEM_ICEPATH1_HM_WATERFALL
#define FLAG_ITEM_ICEPATH1_HM_WATERFALL  0x1077
#endif
#ifndef FLAG_ITEM_ICEPATH1_PP_UP
#define FLAG_ITEM_ICEPATH1_PP_UP  0x1078
#endif
#ifndef FLAG_ITEM_ICEPATH1_PROTEIN
#define FLAG_ITEM_ICEPATH1_PROTEIN  0x1079
#endif
#ifndef FLAG_ITEM_ICEPATH2_IRON
#define FLAG_ITEM_ICEPATH2_IRON  0x107A
#endif
#ifndef FLAG_ITEM_ICEPATH2_REVIVE
#define FLAG_ITEM_ICEPATH2_REVIVE  0x107B
#endif
#ifndef FLAG_ITEM_ICEPATH3_CARBOS
#define FLAG_ITEM_ICEPATH3_CARBOS  0x107C
#endif
#ifndef FLAG_ITEM_ICEPATH3_FULL_HEAL
#define FLAG_ITEM_ICEPATH3_FULL_HEAL  0x107D
#endif
#ifndef FLAG_ITEM_ICEPATH3_MAX_POTION
#define FLAG_ITEM_ICEPATH3_MAX_POTION  0x107E
#endif
#ifndef FLAG_ITEM_ICEPATH3_NEVER_MELT_ICE
#define FLAG_ITEM_ICEPATH3_NEVER_MELT_ICE  0x107F
#endif
#ifndef FLAG_ITEM_LAKEOFRAGE_FULL_RESTORE
#define FLAG_ITEM_LAKEOFRAGE_FULL_RESTORE  0x1080
#endif
#ifndef FLAG_ITEM_LAKEOFRAGE_MAX_REVIVE
#define FLAG_ITEM_LAKEOFRAGE_MAX_REVIVE  0x1081
#endif
#ifndef FLAG_ITEM_LAKEOFRAGE_RED_FLUTE
#define FLAG_ITEM_LAKEOFRAGE_RED_FLUTE  0x1082
#endif
#ifndef FLAG_ITEM_LIGHTHOUSE_ETHER
#define FLAG_ITEM_LIGHTHOUSE_ETHER  0x1083
#endif
#ifndef FLAG_ITEM_LIGHTHOUSE_HYPER_POTION
#define FLAG_ITEM_LIGHTHOUSE_HYPER_POTION  0x1084
#endif
#ifndef FLAG_ITEM_LIGHTHOUSE_PROTEIN
#define FLAG_ITEM_LIGHTHOUSE_PROTEIN  0x1085
#endif
#ifndef FLAG_ITEM_LIGHTHOUSE_RARE_CANDY
#define FLAG_ITEM_LIGHTHOUSE_RARE_CANDY  0x1086
#endif
#ifndef FLAG_ITEM_MTMORTAR1_ELIXIR
#define FLAG_ITEM_MTMORTAR1_ELIXIR  0x1087
#endif
#ifndef FLAG_ITEM_MTMORTAR1_REVIVE
#define FLAG_ITEM_MTMORTAR1_REVIVE  0x1088
#endif
#ifndef FLAG_ITEM_MTMORTAR2_ESCAPE_ROPE
#define FLAG_ITEM_MTMORTAR2_ESCAPE_ROPE  0x1089
#endif
#ifndef FLAG_ITEM_MTMORTAR2_KINGS_ROCK
#define FLAG_ITEM_MTMORTAR2_KINGS_ROCK  0x108A
#endif
#ifndef FLAG_ITEM_MTMORTAR2_MAX_POTION
#define FLAG_ITEM_MTMORTAR2_MAX_POTION  0x108B
#endif
#ifndef FLAG_ITEM_MTMORTAR2_MAX_REPEL
#define FLAG_ITEM_MTMORTAR2_MAX_REPEL  0x108C
#endif
#ifndef FLAG_ITEM_MTMORTAR2_NUGGET
#define FLAG_ITEM_MTMORTAR2_NUGGET  0x108D
#endif
#ifndef FLAG_ITEM_MTMORTAR2_REVIVE
#define FLAG_ITEM_MTMORTAR2_REVIVE  0x108E
#endif
#ifndef FLAG_ITEM_MTMORTAR2_ULTRA_BALL
#define FLAG_ITEM_MTMORTAR2_ULTRA_BALL  0x108F
#endif
#ifndef FLAG_ITEM_MTMORTAR3_DRAGON_SCALE
#define FLAG_ITEM_MTMORTAR3_DRAGON_SCALE  0x1090
#endif
#ifndef FLAG_ITEM_MTMORTAR3_ELIXIR
#define FLAG_ITEM_MTMORTAR3_ELIXIR  0x1091
#endif
#ifndef FLAG_ITEM_MTMORTAR3_ETHER
#define FLAG_ITEM_MTMORTAR3_ETHER  0x1092
#endif
#ifndef FLAG_ITEM_MTMORTAR3_IRON
#define FLAG_ITEM_MTMORTAR3_IRON  0x1093
#endif
#ifndef FLAG_ITEM_MTMORTAR3_MAX_REVIVE
#define FLAG_ITEM_MTMORTAR3_MAX_REVIVE  0x1094
#endif
#ifndef FLAG_ITEM_MTMORTAR3_RARE_CANDY
#define FLAG_ITEM_MTMORTAR3_RARE_CANDY  0x1095
#endif
#ifndef FLAG_ITEM_MTMORTAR4_CARBOS
#define FLAG_ITEM_MTMORTAR4_CARBOS  0x1096
#endif
#ifndef FLAG_ITEM_MTMORTAR4_HYPER_POTION
#define FLAG_ITEM_MTMORTAR4_HYPER_POTION  0x1097
#endif
#ifndef FLAG_ITEM_MTMORTAR4_MAX_ETHER
#define FLAG_ITEM_MTMORTAR4_MAX_ETHER  0x1098
#endif
#ifndef FLAG_ITEM_MTMORTAR4_MAX_REVIVE
#define FLAG_ITEM_MTMORTAR4_MAX_REVIVE  0x1099
#endif
#ifndef FLAG_ITEM_MTMORTAR4_PP_UP
#define FLAG_ITEM_MTMORTAR4_PP_UP  0x109A
#endif
#ifndef FLAG_ITEM_MTSILVER_DIREHIT
#define FLAG_ITEM_MTSILVER_DIREHIT  0x109B
#endif
#ifndef FLAG_ITEM_MTSILVER_FULLRESTORE
#define FLAG_ITEM_MTSILVER_FULLRESTORE  0x109C
#endif
#ifndef FLAG_ITEM_MTSILVER_MAXPOTION
#define FLAG_ITEM_MTSILVER_MAXPOTION  0x109D
#endif
#ifndef FLAG_ITEM_MTSILVER_NERVERMELTICE
#define FLAG_ITEM_MTSILVER_NERVERMELTICE  0x109E
#endif
#ifndef FLAG_ITEM_MTSILVER_RARECANDY
#define FLAG_ITEM_MTSILVER_RARECANDY  0x109F
#endif
#ifndef FLAG_ITEM_MTSILVER_SPELL_TAG
#define FLAG_ITEM_MTSILVER_SPELL_TAG  0x10A0
#endif
#ifndef FLAG_ITEM_MTSILVER_ULTRABALL
#define FLAG_ITEM_MTSILVER_ULTRABALL  0x10A1
#endif
#ifndef FLAG_ITEM_NATIONAL_PARK_SOOTHE_BELL
#define FLAG_ITEM_NATIONAL_PARK_SOOTHE_BELL  0x10A2
#endif
#ifndef FLAG_ITEM_NATIONAL_PARK_TM_DIG
#define FLAG_ITEM_NATIONAL_PARK_TM_DIG  0x10A3
#endif
#ifndef FLAG_ITEM_OLD_AMBER
#define FLAG_ITEM_OLD_AMBER  0x10A4
#endif
#ifndef FLAG_ITEM_OLIVINE_TM_SHOCKWAVE
#define FLAG_ITEM_OLIVINE_TM_SHOCKWAVE  0x10A5
#endif
#ifndef FLAG_ITEM_ROUTE_29_POTION
#define FLAG_ITEM_ROUTE_29_POTION  0x10A6
#endif
#ifndef FLAG_ITEM_ROUTE_31_ANTIDOE
#define FLAG_ITEM_ROUTE_31_ANTIDOE  0x10A7
#endif
#ifndef FLAG_ITEM_ROUTE_31_POKEBALL
#define FLAG_ITEM_ROUTE_31_POKEBALL  0x10A8
#endif
#ifndef FLAG_ITEM_ROUTE_32_GREATBALL
#define FLAG_ITEM_ROUTE_32_GREATBALL  0x10A9
#endif
#ifndef FLAG_ITEM_ROUTE_32_GREATBALL2
#define FLAG_ITEM_ROUTE_32_GREATBALL2  0x10AA
#endif
#ifndef FLAG_ITEM_ROUTE_32_POTION
#define FLAG_ITEM_ROUTE_32_POTION  0x10AB
#endif
#ifndef FLAG_ITEM_ROUTE_32_SUPERPOTION
#define FLAG_ITEM_ROUTE_32_SUPERPOTION  0x10AC
#endif
#ifndef FLAG_ITEM_ROUTE27_MOONSTONE
#define FLAG_ITEM_ROUTE27_MOONSTONE  0x10AD
#endif
#ifndef FLAG_ITEM_ROUTE27_RARECANDY
#define FLAG_ITEM_ROUTE27_RARECANDY  0x10AE
#endif
#ifndef FLAG_ITEM_ROUTE27_REVIVE
#define FLAG_ITEM_ROUTE27_REVIVE  0x10AF
#endif
#ifndef FLAG_ITEM_ROUTE27_SOLARBEAM
#define FLAG_ITEM_ROUTE27_SOLARBEAM  0x10B0
#endif
#ifndef FLAG_ITEM_ROUTE34_RARECANDY
#define FLAG_ITEM_ROUTE34_RARECANDY  0x10B1
#endif
#ifndef FLAG_ITEM_ROUTE34_SOFTSAND
#define FLAG_ITEM_ROUTE34_SOFTSAND  0x10B2
#endif
#ifndef FLAG_ITEM_ROUTE34_SUPERPOTION
#define FLAG_ITEM_ROUTE34_SUPERPOTION  0x10B3
#endif
#ifndef FLAG_ITEM_ROUTE35_BIG_NUGGET
#define FLAG_ITEM_ROUTE35_BIG_NUGGET  0x10B4
#endif
#ifndef FLAG_ITEM_ROUTE35_PARALYZE_HEAL
#define FLAG_ITEM_ROUTE35_PARALYZE_HEAL  0x10B5
#endif
#ifndef FLAG_ITEM_ROUTE35_ROCK_TOMB
#define FLAG_ITEM_ROUTE35_ROCK_TOMB  0x10B6
#endif
#ifndef FLAG_ITEM_ROUTE38_LAX_INCENSE
#define FLAG_ITEM_ROUTE38_LAX_INCENSE  0x10B7
#endif
#ifndef FLAG_ITEM_ROUTE39_NUGGET
#define FLAG_ITEM_ROUTE39_NUGGET  0x10B8
#endif
#ifndef FLAG_ITEM_ROUTE39_TM_BRICK_BREAK
#define FLAG_ITEM_ROUTE39_TM_BRICK_BREAK  0x10B9
#endif
#ifndef FLAG_ITEM_RUINSOFALPH_CHARCOAL
#define FLAG_ITEM_RUINSOFALPH_CHARCOAL  0x10BA
#endif
#ifndef FLAG_ITEM_RUINSOFALPH_ENERGY_POWDER
#define FLAG_ITEM_RUINSOFALPH_ENERGY_POWDER  0x10BB
#endif
#ifndef FLAG_ITEM_RUINSOFALPH_ENERGY_ROOT
#define FLAG_ITEM_RUINSOFALPH_ENERGY_ROOT  0x10BC
#endif
#ifndef FLAG_ITEM_RUINSOFALPH_HEAL_POWDER_1
#define FLAG_ITEM_RUINSOFALPH_HEAL_POWDER_1  0x10BD
#endif
#ifndef FLAG_ITEM_RUINSOFALPH_HEAL_POWDER_2
#define FLAG_ITEM_RUINSOFALPH_HEAL_POWDER_2  0x10BE
#endif
#ifndef FLAG_ITEM_RUINSOFALPH_LUM_BERRY_1
#define FLAG_ITEM_RUINSOFALPH_LUM_BERRY_1  0x10BF
#endif
#ifndef FLAG_ITEM_RUINSOFALPH_LUM_BERRY_2
#define FLAG_ITEM_RUINSOFALPH_LUM_BERRY_2  0x10C0
#endif
#ifndef FLAG_ITEM_RUINSOFALPH_MAX_REVIVE_1
#define FLAG_ITEM_RUINSOFALPH_MAX_REVIVE_1  0x10C1
#endif
#ifndef FLAG_ITEM_RUINSOFALPH_MOON_STONE
#define FLAG_ITEM_RUINSOFALPH_MOON_STONE  0x10C2
#endif
#ifndef FLAG_ITEM_RUINSOFALPH_ORAN_BERRY
#define FLAG_ITEM_RUINSOFALPH_ORAN_BERRY  0x10C3
#endif
#ifndef FLAG_ITEM_RUINSOFALPH_PECHA_BERRY
#define FLAG_ITEM_RUINSOFALPH_PECHA_BERRY  0x10C4
#endif
#ifndef FLAG_ITEM_RUINSOFALPH_SACRED_ASH
#define FLAG_ITEM_RUINSOFALPH_SACRED_ASH  0x10C5
#endif
#ifndef FLAG_ITEM_RUINSOFALPH_SITRUS_BERRY_2
#define FLAG_ITEM_RUINSOFALPH_SITRUS_BERRY_2  0x10C6
#endif
#ifndef FLAG_ITEM_RUINSOFALPH_STAR_PIECE
#define FLAG_ITEM_RUINSOFALPH_STAR_PIECE  0x10C7
#endif
#ifndef FLAG_ITEM_RUINSOFALPH_STARDUST
#define FLAG_ITEM_RUINSOFALPH_STARDUST  0x10C8
#endif
#ifndef FLAG_ITEM_RUINSOFALPH_WATER_STONE
#define FLAG_ITEM_RUINSOFALPH_WATER_STONE  0x10C9
#endif
#ifndef FLAG_ITEM_SLOWPOKE_WELL_FULL_HEAL
#define FLAG_ITEM_SLOWPOKE_WELL_FULL_HEAL  0x10CA
#endif
#ifndef FLAG_ITEM_SLOWPOKE_WELL_GREAT_BALL
#define FLAG_ITEM_SLOWPOKE_WELL_GREAT_BALL  0x10CB
#endif
#ifndef FLAG_ITEM_SLOWPOKE_WELL_KINGS_ROCK
#define FLAG_ITEM_SLOWPOKE_WELL_KINGS_ROCK  0x10CC
#endif
#ifndef FLAG_ITEM_SLOWPOKE_WELL_SUPER_POTION
#define FLAG_ITEM_SLOWPOKE_WELL_SUPER_POTION  0x10CD
#endif
#ifndef FLAG_ITEM_SLOWPOKE_WELL_SUPER_POTION2
#define FLAG_ITEM_SLOWPOKE_WELL_SUPER_POTION2  0x10CE
#endif
#ifndef FLAG_ITEM_SPROUT_TOWER_ESCAPE_ROPE
#define FLAG_ITEM_SPROUT_TOWER_ESCAPE_ROPE  0x10CF
#endif
#ifndef FLAG_ITEM_SPROUT_TOWER_PARALYZE_HEAL
#define FLAG_ITEM_SPROUT_TOWER_PARALYZE_HEAL  0x10D0
#endif
#ifndef FLAG_ITEM_SPROUT_TOWER_POTION
#define FLAG_ITEM_SPROUT_TOWER_POTION  0x10D1
#endif
#ifndef FLAG_ITEM_SPROUT_TOWER_X_DEFEND
#define FLAG_ITEM_SPROUT_TOWER_X_DEFEND  0x10D2
#endif
#ifndef FLAG_ITEM_UNION_CAVE_AWAKENING
#define FLAG_ITEM_UNION_CAVE_AWAKENING  0x10D3
#endif
#ifndef FLAG_ITEM_UNION_CAVE_ETHER
#define FLAG_ITEM_UNION_CAVE_ETHER  0x10D4
#endif
#ifndef FLAG_ITEM_UNION_CAVE_GREAT_BALL
#define FLAG_ITEM_UNION_CAVE_GREAT_BALL  0x10D5
#endif
#ifndef FLAG_ITEM_UNION_CAVE_HYPERPOTION
#define FLAG_ITEM_UNION_CAVE_HYPERPOTION  0x10D6
#endif
#ifndef FLAG_ITEM_UNION_CAVE_MAXREVIVE
#define FLAG_ITEM_UNION_CAVE_MAXREVIVE  0x10D7
#endif
#ifndef FLAG_ITEM_UNION_CAVE_POTION
#define FLAG_ITEM_UNION_CAVE_POTION  0x10D8
#endif
#ifndef FLAG_ITEM_UNION_CAVE_SECRET_POWER
#define FLAG_ITEM_UNION_CAVE_SECRET_POWER  0x10D9
#endif
#ifndef FLAG_ITEM_UNION_CAVE_X_ATTACK
#define FLAG_ITEM_UNION_CAVE_X_ATTACK  0x10DA
#endif
#ifndef FLAG_ITEM_UNION_CAVE_X_DEFEND
#define FLAG_ITEM_UNION_CAVE_X_DEFEND  0x10DB
#endif
#ifndef FLAG_ITEM_VIOLET_CITY_HYPER_POTION
#define FLAG_ITEM_VIOLET_CITY_HYPER_POTION  0x10DC
#endif
#ifndef FLAG_ITEM_VIOLET_CITY_PECHA_BERRY
#define FLAG_ITEM_VIOLET_CITY_PECHA_BERRY  0x10DD
#endif
#ifndef FLAG_ITEM_VIOLET_CITY_RARE_CANDY
#define FLAG_ITEM_VIOLET_CITY_RARE_CANDY  0x10DE
#endif
#ifndef FLAG_ITEM_WHIRL_ISLANDS_1F_FULL_RESTORE
#define FLAG_ITEM_WHIRL_ISLANDS_1F_FULL_RESTORE  0x10DF
#endif
#ifndef FLAG_ITEM_WHIRL_ISLANDS_1F_GUARD_SPEC
#define FLAG_ITEM_WHIRL_ISLANDS_1F_GUARD_SPEC  0x10E0
#endif
#ifndef FLAG_ITEM_WHIRL_ISLANDS_1F_RARE_CANDY
#define FLAG_ITEM_WHIRL_ISLANDS_1F_RARE_CANDY  0x10E1
#endif
#ifndef FLAG_ITEM_WHIRL_ISLANDS_1F_ULTRA_BALL
#define FLAG_ITEM_WHIRL_ISLANDS_1F_ULTRA_BALL  0x10E2
#endif
#ifndef FLAG_ITEM_WHIRL_ISLANDS_B1F_FULL_RESTORE
#define FLAG_ITEM_WHIRL_ISLANDS_B1F_FULL_RESTORE  0x10E3
#endif
#ifndef FLAG_ITEM_WHIRL_ISLANDS_B1F_MAX_REVIVE
#define FLAG_ITEM_WHIRL_ISLANDS_B1F_MAX_REVIVE  0x10E4
#endif
#ifndef FLAG_ITEM_WHIRL_ISLANDS_B1F_PP_MAX
#define FLAG_ITEM_WHIRL_ISLANDS_B1F_PP_MAX  0x10E5
#endif
#ifndef FLAG_ITEM_WHIRL_ISLANDS_B2F_BIG_NUGGET
#define FLAG_ITEM_WHIRL_ISLANDS_B2F_BIG_NUGGET  0x10E6
#endif
#ifndef FLAG_ITEM_WHIRL_ISLANDS_B2F_CALCIUM
#define FLAG_ITEM_WHIRL_ISLANDS_B2F_CALCIUM  0x10E7
#endif
#ifndef FLAG_ITEM_WHIRL_ISLANDS_B2F_CARBOS
#define FLAG_ITEM_WHIRL_ISLANDS_B2F_CARBOS  0x10E8
#endif
#ifndef FLAG_ITEM_WHIRL_ISLANDS_B2F_ESCAPE_ROPE
#define FLAG_ITEM_WHIRL_ISLANDS_B2F_ESCAPE_ROPE  0x10E9
#endif
#ifndef FLAG_ITEM_WHIRL_ISLANDS_B2F_FULL_RESTORE
#define FLAG_ITEM_WHIRL_ISLANDS_B2F_FULL_RESTORE  0x10EA
#endif
#ifndef FLAG_MINTS_CLERK
#define FLAG_MINTS_CLERK  0x10EB
#endif
#ifndef FLAG_MOM_VISITED
#define FLAG_MOM_VISITED  0x10EC
#endif
#ifndef FLAG_NIGHT_POKEMON
#define FLAG_NIGHT_POKEMON  0x10ED
#endif
#ifndef FLAG_SAFARI_ZONE_EAST_EXPANSION
#define FLAG_SAFARI_ZONE_EAST_EXPANSION  0x10EE
#endif
#ifndef FLAG_SAFARI_ZONE_WEST_EXPANSION
#define FLAG_SAFARI_ZONE_WEST_EXPANSION  0x10EF
#endif


// Additional Johto flags from scripts (0x10F0-0x117D)
#ifndef FLAG_AERODACTYL_BROUGHT
#define FLAG_AERODACTYL_BROUGHT  0x10F0
#endif
#ifndef FLAG_BEAT_KIYO
#define FLAG_BEAT_KIYO  0x10F1
#endif
#ifndef FLAG_BLACKTHORN_NPC_TRADE_COMPLETED
#define FLAG_BLACKTHORN_NPC_TRADE_COMPLETED  0x10F2
#endif
#ifndef FLAG_CAUGHT_CELEBI
#define FLAG_CAUGHT_CELEBI  0x10F3
#endif
#ifndef FLAG_CAUGHT_ENTEI
#define FLAG_CAUGHT_ENTEI  0x10F4
#endif
#ifndef FLAG_CAUGHT_RAIKOU
#define FLAG_CAUGHT_RAIKOU  0x10F5
#endif
#ifndef FLAG_COMPLETED_AERODACTYL_PUZZLE
#define FLAG_COMPLETED_AERODACTYL_PUZZLE  0x10F6
#endif
#ifndef FLAG_COMPLETED_HOOH_PUZZLE
#define FLAG_COMPLETED_HOOH_PUZZLE  0x10F7
#endif
#ifndef FLAG_COMPLETED_KABUTO_PUZZLE
#define FLAG_COMPLETED_KABUTO_PUZZLE  0x10F8
#endif
#ifndef FLAG_COMPLETED_OMANYTE_PUZZLE
#define FLAG_COMPLETED_OMANYTE_PUZZLE  0x10F9
#endif
#ifndef FLAG_COMPLETED_SWITCHES
#define FLAG_COMPLETED_SWITCHES  0x10FA
#endif
#ifndef FLAG_DEFEATED_AZALEA_TOWN_GYM
#define FLAG_DEFEATED_AZALEA_TOWN_GYM  0x10FB
#endif
#ifndef FLAG_DEFEATED_BLACKTHORN_GYM
#define FLAG_DEFEATED_BLACKTHORN_GYM  0x10FC
#endif
#ifndef FLAG_DEFEATED_CIANWOOD_GYM
#define FLAG_DEFEATED_CIANWOOD_GYM  0x10FD
#endif
#ifndef FLAG_DEFEATED_ECRUTEAK_CITY_GYM
#define FLAG_DEFEATED_ECRUTEAK_CITY_GYM  0x10FE
#endif
#ifndef FLAG_DEFEATED_GOLDENROD_CITY_GYM
#define FLAG_DEFEATED_GOLDENROD_CITY_GYM  0x10FF
#endif
#ifndef FLAG_DEFEATED_MAHOGANY_TOWN_GYM
#define FLAG_DEFEATED_MAHOGANY_TOWN_GYM  0x1100
#endif
#ifndef FLAG_DEFEATED_OLIVINE_CITY_GYM
#define FLAG_DEFEATED_OLIVINE_CITY_GYM  0x1101
#endif
#ifndef FLAG_DEFEATED_RED
#define FLAG_DEFEATED_RED  0x1102
#endif
#ifndef FLAG_DEFEATED_VIOLET_GYM
#define FLAG_DEFEATED_VIOLET_GYM  0x1103
#endif
#ifndef FLAG_EXP_SHARE
#define FLAG_EXP_SHARE  0x1104
#endif
#ifndef FLAG_FINITE_TMS
#define FLAG_FINITE_TMS  0x1105
#endif
#ifndef FLAG_GET_HEADBUTT
#define FLAG_GET_HEADBUTT  0x1106
#endif
#ifndef FLAG_GOLDENROD_MACHOKE_1
#define FLAG_GOLDENROD_MACHOKE_1  0x1107
#endif
#ifndef FLAG_GOLDENROD_MACHOKE_2
#define FLAG_GOLDENROD_MACHOKE_2  0x1108
#endif
#ifndef FLAG_GOLDENROD_MACHOKE_3
#define FLAG_GOLDENROD_MACHOKE_3  0x1109
#endif
#ifndef FLAG_GOLDENROD_NPC_TRADE_COMPLETED
#define FLAG_GOLDENROD_NPC_TRADE_COMPLETED  0x110A
#endif
#ifndef FLAG_GOLDENROD_SWITCH_1
#define FLAG_GOLDENROD_SWITCH_1  0x110B
#endif
#ifndef FLAG_GOLDENROD_SWITCH_2
#define FLAG_GOLDENROD_SWITCH_2  0x110C
#endif
#ifndef FLAG_GOLDENROD_SWITCH_3
#define FLAG_GOLDENROD_SWITCH_3  0x110D
#endif
#ifndef FLAG_GOLDENROD_SWITCH_ORDER
#define FLAG_GOLDENROD_SWITCH_ORDER  0x110E
#endif
#ifndef FLAG_GOT_BERRY_ROUTE_30_HOUSE
#define FLAG_GOT_BERRY_ROUTE_30_HOUSE  0x110F
#endif
#ifndef FLAG_GOT_BLACK_BELT
#define FLAG_GOT_BLACK_BELT  0x1110
#endif
#ifndef FLAG_GOT_BLACK_GLASSES
#define FLAG_GOT_BLACK_GLASSES  0x1111
#endif
#ifndef FLAG_GOT_CHARCOAL
#define FLAG_GOT_CHARCOAL  0x1112
#endif
#ifndef FLAG_GOT_DRATINI
#define FLAG_GOT_DRATINI  0x1113
#endif
#ifndef FLAG_GOT_FRUSTRATION
#define FLAG_GOT_FRUSTRATION  0x1114
#endif
#ifndef FLAG_GOT_HARD_STONE
#define FLAG_GOT_HARD_STONE  0x1115
#endif
#ifndef FLAG_GOT_HIDDEN_POWER
#define FLAG_GOT_HIDDEN_POWER  0x1116
#endif
#ifndef FLAG_GOT_MAGNET
#define FLAG_GOT_MAGNET  0x1117
#endif
#ifndef FLAG_GOT_MARY_BRIGHT_POWDER
#define FLAG_GOT_MARY_BRIGHT_POWDER  0x1118
#endif
#ifndef FLAG_GOT_MYSTICWATER
#define FLAG_GOT_MYSTICWATER  0x1119
#endif
#ifndef FLAG_GOT_PASSWORD_FROM_ETO
#define FLAG_GOT_PASSWORD_FROM_ETO  0x111A
#endif
#ifndef FLAG_GOT_PASSWORD_FROM_GRUNTF
#define FLAG_GOT_PASSWORD_FROM_GRUNTF  0x111B
#endif
#ifndef FLAG_GOT_POISON_BARB
#define FLAG_GOT_POISON_BARB  0x111C
#endif
#ifndef FLAG_GOT_QUICK_CLAW
#define FLAG_GOT_QUICK_CLAW  0x111D
#endif
#ifndef FLAG_GOT_RETURN
#define FLAG_GOT_RETURN  0x111E
#endif
#ifndef FLAG_GOT_SILK_SCARF
#define FLAG_GOT_SILK_SCARF  0x111F
#endif
#ifndef FLAG_GOT_SKILL_SWAP
#define FLAG_GOT_SKILL_SWAP  0x1120
#endif
#ifndef FLAG_GOT_SPELL_TAG
#define FLAG_GOT_SPELL_TAG  0x1121
#endif
#ifndef FLAG_GOT_TM_FROM_MAHOGANY_COP
#define FLAG_GOT_TM_FROM_MAHOGANY_COP  0x1122
#endif
#ifndef FLAG_GOT_TM_SANDSTORM
#define FLAG_GOT_TM_SANDSTORM  0x1123
#endif
#ifndef FLAG_GOT_TM_SNATCH
#define FLAG_GOT_TM_SNATCH  0x1124
#endif
#ifndef FLAG_GOT_TM_STEEL_WING
#define FLAG_GOT_TM_STEEL_WING  0x1125
#endif
#ifndef FLAG_GOT_TYROGUE
#define FLAG_GOT_TYROGUE  0x1126
#endif
#ifndef FLAG_HIDE_BATTLEFRONTIER_ENGINEER
#define FLAG_HIDE_BATTLEFRONTIER_ENGINEER  0x1127
#endif
#ifndef FLAG_HIDE_CELEBI
#define FLAG_HIDE_CELEBI  0x1128
#endif
#ifndef FLAG_HIDE_DOJO_CHUCK
#define FLAG_HIDE_DOJO_CHUCK  0x1129
#endif
#ifndef FLAG_HIDE_DOJO_CLAIR
#define FLAG_HIDE_DOJO_CLAIR  0x112A
#endif
#ifndef FLAG_HIDE_DOJO_JASMINE
#define FLAG_HIDE_DOJO_JASMINE  0x112B
#endif
#ifndef FLAG_HIDE_DOJO_MORTY
#define FLAG_HIDE_DOJO_MORTY  0x112C
#endif
#ifndef FLAG_HIDE_DOJO_PRYCE
#define FLAG_HIDE_DOJO_PRYCE  0x112D
#endif
#ifndef FLAG_HIDE_DOJO_SABRINA
#define FLAG_HIDE_DOJO_SABRINA  0x112E
#endif
#ifndef FLAG_HIDE_DOJO_WHITNEY
#define FLAG_HIDE_DOJO_WHITNEY  0x112F
#endif
#ifndef FLAG_HIDE_GROUDON
#define FLAG_HIDE_GROUDON  0x1130
#endif
#ifndef FLAG_HIDE_ILEX_FOREST_APPRENTICE
#define FLAG_HIDE_ILEX_FOREST_APPRENTICE  0x1131
#endif
#ifndef FLAG_HIDE_ILEX_FOREST_FARFETCHD_1
#define FLAG_HIDE_ILEX_FOREST_FARFETCHD_1  0x1132
#endif
#ifndef FLAG_HIDE_ILEX_FOREST_FARFETCHD_2
#define FLAG_HIDE_ILEX_FOREST_FARFETCHD_2  0x1133
#endif
#ifndef FLAG_HIDE_ILEX_FOREST_FARFETCHD_3
#define FLAG_HIDE_ILEX_FOREST_FARFETCHD_3  0x1134
#endif
#ifndef FLAG_HIDE_ILEX_FOREST_FARFETCHD_4
#define FLAG_HIDE_ILEX_FOREST_FARFETCHD_4  0x1135
#endif
#ifndef FLAG_HIDE_ILEX_FOREST_KIMONO
#define FLAG_HIDE_ILEX_FOREST_KIMONO  0x1136
#endif
#ifndef FLAG_HIDE_ILEX_FOREST_KURT
#define FLAG_HIDE_ILEX_FOREST_KURT  0x1137
#endif
#ifndef FLAG_HIDE_ILEX_FOREST_MASTER
#define FLAG_HIDE_ILEX_FOREST_MASTER  0x1138
#endif
#ifndef FLAG_HIDE_INDIGO_PLATEAU_MARY_OAK
#define FLAG_HIDE_INDIGO_PLATEAU_MARY_OAK  0x1139
#endif
#ifndef FLAG_HIDE_INDIGO_PLATEAU_SILVER
#define FLAG_HIDE_INDIGO_PLATEAU_SILVER  0x113A
#endif
#ifndef FLAG_HIDE_KYOGRE
#define FLAG_HIDE_KYOGRE  0x113B
#endif
#ifndef FLAG_HIDE_MAHOGANY_COP
#define FLAG_HIDE_MAHOGANY_COP  0x113C
#endif
#ifndef FLAG_HIDE_MAHOGANY_ROCKETS
#define FLAG_HIDE_MAHOGANY_ROCKETS  0x113D
#endif
#ifndef FLAG_HIDE_RADIOTOWER_GATE
#define FLAG_HIDE_RADIOTOWER_GATE  0x113E
#endif
#ifndef FLAG_HIDE_ROCKETHIDEOUT_ELECTRODE1
#define FLAG_HIDE_ROCKETHIDEOUT_ELECTRODE1  0x113F
#endif
#ifndef FLAG_HIDE_ROCKETHIDEOUT_ELECTRODE2
#define FLAG_HIDE_ROCKETHIDEOUT_ELECTRODE2  0x1140
#endif
#ifndef FLAG_HIDE_ROCKETHIDEOUT_ELECTRODE3
#define FLAG_HIDE_ROCKETHIDEOUT_ELECTRODE3  0x1141
#endif
#ifndef FLAG_HIDE_ROCKETHIDEOUT_ROCKETS
#define FLAG_HIDE_ROCKETHIDEOUT_ROCKETS  0x1142
#endif
#ifndef FLAG_HIDE_ROCKETHIDEOUT2_ARIANA_AND_GRUNT
#define FLAG_HIDE_ROCKETHIDEOUT2_ARIANA_AND_GRUNT  0x1143
#endif
#ifndef FLAG_HIDE_ROCKETHIDEOUT2_GATE
#define FLAG_HIDE_ROCKETHIDEOUT2_GATE  0x1144
#endif
#ifndef FLAG_HIDE_ROCKETHIDEOUT2_LANCE_DRAGONITE
#define FLAG_HIDE_ROCKETHIDEOUT2_LANCE_DRAGONITE  0x1145
#endif
#ifndef FLAG_HIDE_ROCKETHIDEOUT2_MURKROWGATE
#define FLAG_HIDE_ROCKETHIDEOUT2_MURKROWGATE  0x1146
#endif
#ifndef FLAG_HIDE_ROCKETHIDEOUT2_MURKROWSTAIRS
#define FLAG_HIDE_ROCKETHIDEOUT2_MURKROWSTAIRS  0x1147
#endif
#ifndef FLAG_HIDE_ROCKETHIDEOUT3_GATE
#define FLAG_HIDE_ROCKETHIDEOUT3_GATE  0x1148
#endif
#ifndef FLAG_HIDE_ROCKETHIDEOUT3_GIOVANNI
#define FLAG_HIDE_ROCKETHIDEOUT3_GIOVANNI  0x1149
#endif
#ifndef FLAG_HIDE_ROCKETHIDEOUT3_MURKROW
#define FLAG_HIDE_ROCKETHIDEOUT3_MURKROW  0x114A
#endif
#ifndef FLAG_HIDE_ROCKETHIDEOUT3_MURKROWSTAIRS
#define FLAG_HIDE_ROCKETHIDEOUT3_MURKROWSTAIRS  0x114B
#endif
#ifndef FLAG_HIDE_ROCKETHIDEOUT3_PETREL
#define FLAG_HIDE_ROCKETHIDEOUT3_PETREL  0x114C
#endif
#ifndef FLAG_HIDE_ROCKETHIDEOUT3_SILVER
#define FLAG_HIDE_ROCKETHIDEOUT3_SILVER  0x114D
#endif
#ifndef FLAG_HIDE_ROUTE42_EUSINE
#define FLAG_HIDE_ROUTE42_EUSINE  0x114E
#endif
#ifndef FLAG_HIDE_ROUTE42_SUICUNE
#define FLAG_HIDE_ROUTE42_SUICUNE  0x114F
#endif
#ifndef FLAG_HIDE_SSAQUA_1F_GRANDPA
#define FLAG_HIDE_SSAQUA_1F_GRANDPA  0x1150
#endif
#ifndef FLAG_HIDE_SSAQUA_CAPTAINS_ROOM_GRANDDAUGHTER
#define FLAG_HIDE_SSAQUA_CAPTAINS_ROOM_GRANDDAUGHTER  0x1151
#endif
#ifndef FLAG_HIDE_SSAQUA_ROOM_SSE_GRANDDAUGHTER
#define FLAG_HIDE_SSAQUA_ROOM_SSE_GRANDDAUGHTER  0x1152
#endif
#ifndef FLAG_HIDE_SSAQUA_SAILOR
#define FLAG_HIDE_SSAQUA_SAILOR  0x1153
#endif
#ifndef FLAG_HIDE_TIN_TOWER_KIMONO_GIRLS
#define FLAG_HIDE_TIN_TOWER_KIMONO_GIRLS  0x1154
#endif
#ifndef FLAG_HIDE_TINTOWER_GUARD
#define FLAG_HIDE_TINTOWER_GUARD  0x1155
#endif
#ifndef FLAG_HIDE_VICTORY_ROAD_SILVER
#define FLAG_HIDE_VICTORY_ROAD_SILVER  0x1156
#endif
#ifndef FLAG_HOOH_BROUGHT
#define FLAG_HOOH_BROUGHT  0x1157
#endif
#ifndef FLAG_INDIGOJUNCTION_HIDE_KANTO_GUARD
#define FLAG_INDIGOJUNCTION_HIDE_KANTO_GUARD  0x1158
#endif
#ifndef FLAG_INDIGOJUNCTION_HIDE_SILVER_GUARD
#define FLAG_INDIGOJUNCTION_HIDE_SILVER_GUARD  0x1159
#endif
#ifndef FLAG_IS_KANTO_CHAMPION
#define FLAG_IS_KANTO_CHAMPION  0x115A
#endif
#ifndef FLAG_ITEM_ICEPATH4_TM_BLIZZARD
#define FLAG_ITEM_ICEPATH4_TM_BLIZZARD  0x115B
#endif
#ifndef FLAG_ITEM_SLOWPOKE_WELL_RAIN_DANCE
#define FLAG_ITEM_SLOWPOKE_WELL_RAIN_DANCE  0x115C
#endif
#ifndef FLAG_KABUTO_BROUGHT
#define FLAG_KABUTO_BROUGHT  0x115D
#endif
#ifndef FLAG_KANTO_RADIO_GOT
#define FLAG_KANTO_RADIO_GOT  0x115E
#endif
#ifndef FLAG_MINTS_ENABLED
#define FLAG_MINTS_ENABLED  0x115F
#endif
#ifndef FLAG_MOVE_TUTOR_TAUGHT_HEADBUTT
#define FLAG_MOVE_TUTOR_TAUGHT_HEADBUTT  0x1160
#endif
#ifndef FLAG_OLIVINE_NPC_TRADE_COMPLETED
#define FLAG_OLIVINE_NPC_TRADE_COMPLETED  0x1161
#endif
#ifndef FLAG_OMANYTE_BROUGHT
#define FLAG_OMANYTE_BROUGHT  0x1162
#endif
#ifndef FLAG_RECEIVED_FIRST_BALLS
#define FLAG_RECEIVED_FIRST_BALLS  0x1163
#endif
#ifndef FLAG_RECEIVED_FIRST_POTION
#define FLAG_RECEIVED_FIRST_POTION  0x1164
#endif
#ifndef FLAG_RECEIVED_ODD_EGG
#define FLAG_RECEIVED_ODD_EGG  0x1165
#endif
#ifndef FLAG_RECEIVED_SQUIRTBOTTLE
#define FLAG_RECEIVED_SQUIRTBOTTLE  0x1166
#endif
#ifndef FLAG_RECEIVED_TOGEPI_EGG
#define FLAG_RECEIVED_TOGEPI_EGG  0x1167
#endif
#ifndef FLAG_RELEASED_BEASTS
#define FLAG_RELEASED_BEASTS  0x1168
#endif
#ifndef FLAG_RETURNED_MACHINE_PART
#define FLAG_RETURNED_MACHINE_PART  0x1169
#endif
#ifndef FLAG_ROCKETHIDEOUT_SWITCH
#define FLAG_ROCKETHIDEOUT_SWITCH  0x116A
#endif
#ifndef FLAG_SHOWN_ELM_TOGEPI
#define FLAG_SHOWN_ELM_TOGEPI  0x116B
#endif
#ifndef FLAG_UNLOCKED_GOLDENROD_UNDERGROUND_DOOR
#define FLAG_UNLOCKED_GOLDENROD_UNDERGROUND_DOOR  0x116C
#endif
#ifndef FLAG_VIOLET_NPC_TRADE_COMPLETED
#define FLAG_VIOLET_NPC_TRADE_COMPLETED  0x116D
#endif
#ifndef FLAG_VISITED_AZALEA_TOWN
#define FLAG_VISITED_AZALEA_TOWN  0x116E
#endif
#ifndef FLAG_VISITED_BLACKTHORN_CITY
#define FLAG_VISITED_BLACKTHORN_CITY  0x116F
#endif
#ifndef FLAG_VISITED_CHERRYGROVE_CITY
#define FLAG_VISITED_CHERRYGROVE_CITY  0x1170
#endif
#ifndef FLAG_VISITED_CIANWOOD_CITY
#define FLAG_VISITED_CIANWOOD_CITY  0x1171
#endif
#ifndef FLAG_VISITED_ECRUTEAK_CITY
#define FLAG_VISITED_ECRUTEAK_CITY  0x1172
#endif
#ifndef FLAG_VISITED_GOLDENROD_CITY
#define FLAG_VISITED_GOLDENROD_CITY  0x1173
#endif
#ifndef FLAG_VISITED_KANTO
#define FLAG_VISITED_KANTO  0x1174
#endif
#ifndef FLAG_VISITED_LAKE_OF_RAGE
#define FLAG_VISITED_LAKE_OF_RAGE  0x1175
#endif
#ifndef FLAG_VISITED_MAHOGANY_TOWN
#define FLAG_VISITED_MAHOGANY_TOWN  0x1176
#endif
#ifndef FLAG_VISITED_MT_SILVER
#define FLAG_VISITED_MT_SILVER  0x1177
#endif
#ifndef FLAG_VISITED_NEWBARK_TOWN
#define FLAG_VISITED_NEWBARK_TOWN  0x1178
#endif
#ifndef FLAG_VISITED_OLIVINE_CITY
#define FLAG_VISITED_OLIVINE_CITY  0x1179
#endif
#ifndef FLAG_VISITED_RECEPTION_GATE
#define FLAG_VISITED_RECEPTION_GATE  0x117A
#endif
#ifndef FLAG_VISITED_SAFARI_ZONE_GATE
#define FLAG_VISITED_SAFARI_ZONE_GATE  0x117B
#endif
#ifndef FLAG_VISITED_VERMILION_CITY
#define FLAG_VISITED_VERMILION_CITY  0x117C
#endif
#ifndef FLAG_VISITED_VIOLET_CITY
#define FLAG_VISITED_VIOLET_CITY  0x117D
#endif

// Johto haircut and system flags not in HnS's base flag range
#ifndef FLAG_DAILY_HAIRCUT1_RECEIVED
#define FLAG_DAILY_HAIRCUT1_RECEIVED  0x117E
#endif
#ifndef FLAG_DAILY_HAIRCUT2_RECEIVED
#define FLAG_DAILY_HAIRCUT2_RECEIVED  0x117F
#endif
#ifndef FLAG_SYS_LAKE_OF_RAGE_TIDE
#define FLAG_SYS_LAKE_OF_RAGE_TIDE  0x1180
#endif
#ifndef FLAG_SYS_PC_BILL
#define FLAG_SYS_PC_BILL  0x1181
#endif

#undef JOHTO_FLAGS_END
#define JOHTO_FLAGS_END  0x1181

#endif // GUARD_CONSTANTS_FLAGS_JOHTO_H
