#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"
#include "constants/opponents_frlg.h"

// Remap ALL FRLG trainer constants to 900+frlgId so they don't collide with
// Emerald trainer IDs when trainers_frlg.h is included in the Emerald build.
// Generated from include/constants/opponents_frlg.h with OFFSET=900.
#if !IS_FRLG
#undef  TRAINER_YOUNGSTER_BEN
#define TRAINER_YOUNGSTER_BEN 901
#undef  TRAINER_YOUNGSTER_CALVIN
#define TRAINER_YOUNGSTER_CALVIN 902
#undef  TRAINER_YOUNGSTER_JOSH
#define TRAINER_YOUNGSTER_JOSH 903
#undef  TRAINER_YOUNGSTER_TIMMY
#define TRAINER_YOUNGSTER_TIMMY 904
#undef  TRAINER_YOUNGSTER_JOEY
#define TRAINER_YOUNGSTER_JOEY 905
#undef  TRAINER_YOUNGSTER_DAN
#define TRAINER_YOUNGSTER_DAN 906
#undef  TRAINER_YOUNGSTER_CHAD
#define TRAINER_YOUNGSTER_CHAD 907
#undef  TRAINER_YOUNGSTER_TYLER
#define TRAINER_YOUNGSTER_TYLER 908
#undef  TRAINER_YOUNGSTER_EDDIE
#define TRAINER_YOUNGSTER_EDDIE 909
#undef  TRAINER_YOUNGSTER_DILLON
#define TRAINER_YOUNGSTER_DILLON 910
#undef  TRAINER_YOUNGSTER_YASU
#define TRAINER_YOUNGSTER_YASU 911
#undef  TRAINER_YOUNGSTER_DAVE
#define TRAINER_YOUNGSTER_DAVE 912
#undef  TRAINER_YOUNGSTER_BEN_2
#define TRAINER_YOUNGSTER_BEN_2 913
#undef  TRAINER_BUG_CATCHER_RICK
#define TRAINER_BUG_CATCHER_RICK 914
#undef  TRAINER_BUG_CATCHER_DOUG
#define TRAINER_BUG_CATCHER_DOUG 915
#undef  TRAINER_BUG_CATCHER_SAMMY
#define TRAINER_BUG_CATCHER_SAMMY 916
#undef  TRAINER_BUG_CATCHER_COLTON
#define TRAINER_BUG_CATCHER_COLTON 917
#undef  TRAINER_BUG_CATCHER_GREG
#define TRAINER_BUG_CATCHER_GREG 918
#undef  TRAINER_BUG_CATCHER_JAMES
#define TRAINER_BUG_CATCHER_JAMES 919
#undef  TRAINER_BUG_CATCHER_KENT
#define TRAINER_BUG_CATCHER_KENT 920
#undef  TRAINER_BUG_CATCHER_ROBBY
#define TRAINER_BUG_CATCHER_ROBBY 921
#undef  TRAINER_BUG_CATCHER_CALE
#define TRAINER_BUG_CATCHER_CALE 922
#undef  TRAINER_BUG_CATCHER_KEIGO
#define TRAINER_BUG_CATCHER_KEIGO 923
#undef  TRAINER_BUG_CATCHER_ELIJAH
#define TRAINER_BUG_CATCHER_ELIJAH 924
#undef  TRAINER_BUG_CATCHER_BRENT
#define TRAINER_BUG_CATCHER_BRENT 925
#undef  TRAINER_BUG_CATCHER_CONNER
#define TRAINER_BUG_CATCHER_CONNER 926
#undef  TRAINER_LASS_JANICE
#define TRAINER_LASS_JANICE 927
#undef  TRAINER_LASS_SALLY
#define TRAINER_LASS_SALLY 928
#undef  TRAINER_LASS_ROBIN
#define TRAINER_LASS_ROBIN 929
#undef  TRAINER_LASS_CRISSY
#define TRAINER_LASS_CRISSY 930
#undef  TRAINER_LASS_MIRIAM
#define TRAINER_LASS_MIRIAM 931
#undef  TRAINER_LASS_IRIS
#define TRAINER_LASS_IRIS 932
#undef  TRAINER_LASS_RELI
#define TRAINER_LASS_RELI 933
#undef  TRAINER_LASS_ALI
#define TRAINER_LASS_ALI 934
#undef  TRAINER_LASS_HALEY
#define TRAINER_LASS_HALEY 935
#undef  TRAINER_LASS_ANN
#define TRAINER_LASS_ANN 936
#undef  TRAINER_LASS_DAWN
#define TRAINER_LASS_DAWN 937
#undef  TRAINER_LASS_PAIGE
#define TRAINER_LASS_PAIGE 938
#undef  TRAINER_LASS_ANDREA
#define TRAINER_LASS_ANDREA 939
#undef  TRAINER_LASS_MEGAN
#define TRAINER_LASS_MEGAN 940
#undef  TRAINER_LASS_JULIA
#define TRAINER_LASS_JULIA 941
#undef  TRAINER_LASS_KAY
#define TRAINER_LASS_KAY 942
#undef  TRAINER_LASS_LISA
#define TRAINER_LASS_LISA 943
#undef  TRAINER_SAILOR_EDMOND
#define TRAINER_SAILOR_EDMOND 944
#undef  TRAINER_SAILOR_TREVOR
#define TRAINER_SAILOR_TREVOR 945
#undef  TRAINER_SAILOR_LEONARD
#define TRAINER_SAILOR_LEONARD 946
#undef  TRAINER_SAILOR_DUNCAN
#define TRAINER_SAILOR_DUNCAN 947
#undef  TRAINER_SAILOR_HUEY
#define TRAINER_SAILOR_HUEY 948
#undef  TRAINER_SAILOR_DYLAN
#define TRAINER_SAILOR_DYLAN 949
#undef  TRAINER_SAILOR_PHILLIP
#define TRAINER_SAILOR_PHILLIP 950
#undef  TRAINER_SAILOR_DWAYNE
#define TRAINER_SAILOR_DWAYNE 951
#undef  TRAINER_CAMPER_LIAM
#define TRAINER_CAMPER_LIAM 952
#undef  TRAINER_CAMPER_SHANE
#define TRAINER_CAMPER_SHANE 953
#undef  TRAINER_CAMPER_ETHAN
#define TRAINER_CAMPER_ETHAN 954
#undef  TRAINER_CAMPER_RICKY
#define TRAINER_CAMPER_RICKY 955
#undef  TRAINER_CAMPER_JEFF
#define TRAINER_CAMPER_JEFF 956
#undef  TRAINER_CAMPER_CHRIS
#define TRAINER_CAMPER_CHRIS 957
#undef  TRAINER_CAMPER_DREW
#define TRAINER_CAMPER_DREW 958
#undef  TRAINER_PICNICKER_DIANA
#define TRAINER_PICNICKER_DIANA 959
#undef  TRAINER_PICNICKER_NANCY
#define TRAINER_PICNICKER_NANCY 960
#undef  TRAINER_PICNICKER_ISABELLE
#define TRAINER_PICNICKER_ISABELLE 961
#undef  TRAINER_PICNICKER_KELSEY
#define TRAINER_PICNICKER_KELSEY 962
#undef  TRAINER_PICNICKER_ALICIA
#define TRAINER_PICNICKER_ALICIA 963
#undef  TRAINER_PICNICKER_CAITLIN
#define TRAINER_PICNICKER_CAITLIN 964
#undef  TRAINER_PICNICKER_HEIDI
#define TRAINER_PICNICKER_HEIDI 965
#undef  TRAINER_PICNICKER_CAROL
#define TRAINER_PICNICKER_CAROL 966
#undef  TRAINER_PICNICKER_SOFIA
#define TRAINER_PICNICKER_SOFIA 967
#undef  TRAINER_PICNICKER_MARTHA
#define TRAINER_PICNICKER_MARTHA 968
#undef  TRAINER_PICNICKER_TINA
#define TRAINER_PICNICKER_TINA 969
#undef  TRAINER_PICNICKER_HANNAH
#define TRAINER_PICNICKER_HANNAH 970
#undef  TRAINER_POKEMANIAC_MARK
#define TRAINER_POKEMANIAC_MARK 971
#undef  TRAINER_POKEMANIAC_HERMAN
#define TRAINER_POKEMANIAC_HERMAN 972
#undef  TRAINER_POKEMANIAC_COOPER
#define TRAINER_POKEMANIAC_COOPER 973
#undef  TRAINER_POKEMANIAC_STEVE
#define TRAINER_POKEMANIAC_STEVE 974
#undef  TRAINER_POKEMANIAC_WINSTON
#define TRAINER_POKEMANIAC_WINSTON 975
#undef  TRAINER_POKEMANIAC_DAWSON
#define TRAINER_POKEMANIAC_DAWSON 976
#undef  TRAINER_POKEMANIAC_ASHTON
#define TRAINER_POKEMANIAC_ASHTON 977
#undef  TRAINER_SUPER_NERD_JOVAN
#define TRAINER_SUPER_NERD_JOVAN 978
#undef  TRAINER_SUPER_NERD_MIGUEL
#define TRAINER_SUPER_NERD_MIGUEL 979
#undef  TRAINER_SUPER_NERD_AIDAN
#define TRAINER_SUPER_NERD_AIDAN 980
#undef  TRAINER_SUPER_NERD_GLENN
#define TRAINER_SUPER_NERD_GLENN 981
#undef  TRAINER_SUPER_NERD_LESLIE
#define TRAINER_SUPER_NERD_LESLIE 982
#undef  TRAINER_SUPER_NERD_ERIK
#define TRAINER_SUPER_NERD_ERIK 983
#undef  TRAINER_SUPER_NERD_AVERY
#define TRAINER_SUPER_NERD_AVERY 984
#undef  TRAINER_SUPER_NERD_DEREK
#define TRAINER_SUPER_NERD_DEREK 985
#undef  TRAINER_SUPER_NERD_ZAC
#define TRAINER_SUPER_NERD_ZAC 986
#undef  TRAINER_HIKER_MARCOS
#define TRAINER_HIKER_MARCOS 987
#undef  TRAINER_HIKER_FRANKLIN
#define TRAINER_HIKER_FRANKLIN 988
#undef  TRAINER_HIKER_NOB
#define TRAINER_HIKER_NOB 989
#undef  TRAINER_HIKER_WAYNE
#define TRAINER_HIKER_WAYNE 990
#undef  TRAINER_HIKER_ALAN
#define TRAINER_HIKER_ALAN 991
#undef  TRAINER_HIKER_BRICE
#define TRAINER_HIKER_BRICE 992
#undef  TRAINER_HIKER_CLARK
#define TRAINER_HIKER_CLARK 993
#undef  TRAINER_HIKER_TRENT
#define TRAINER_HIKER_TRENT 994
#undef  TRAINER_HIKER_DUDLEY
#define TRAINER_HIKER_DUDLEY 995
#undef  TRAINER_HIKER_ALLEN
#define TRAINER_HIKER_ALLEN 996
#undef  TRAINER_HIKER_ERIC
#define TRAINER_HIKER_ERIC 997
#undef  TRAINER_HIKER_LENNY
#define TRAINER_HIKER_LENNY 998
#undef  TRAINER_HIKER_OLIVER
#define TRAINER_HIKER_OLIVER 999
#undef  TRAINER_HIKER_LUCAS
#define TRAINER_HIKER_LUCAS 1000
#undef  TRAINER_BIKER_JARED
#define TRAINER_BIKER_JARED 1001
#undef  TRAINER_BIKER_MALIK
#define TRAINER_BIKER_MALIK 1002
#undef  TRAINER_BIKER_ERNEST
#define TRAINER_BIKER_ERNEST 1003
#undef  TRAINER_BIKER_ALEX
#define TRAINER_BIKER_ALEX 1004
#undef  TRAINER_BIKER_LAO
#define TRAINER_BIKER_LAO 1005
#undef  TRAINER_BIKER_HIDEO
#define TRAINER_BIKER_HIDEO 1006
#undef  TRAINER_BIKER_RUBEN
#define TRAINER_BIKER_RUBEN 1007
#undef  TRAINER_BIKER_BILLY
#define TRAINER_BIKER_BILLY 1008
#undef  TRAINER_BIKER_NIKOLAS
#define TRAINER_BIKER_NIKOLAS 1009
#undef  TRAINER_BIKER_JAXON
#define TRAINER_BIKER_JAXON 1010
#undef  TRAINER_BIKER_WILLIAM
#define TRAINER_BIKER_WILLIAM 1011
#undef  TRAINER_BIKER_LUKAS
#define TRAINER_BIKER_LUKAS 1012
#undef  TRAINER_BIKER_ISAAC
#define TRAINER_BIKER_ISAAC 1013
#undef  TRAINER_BIKER_GERALD
#define TRAINER_BIKER_GERALD 1014
#undef  TRAINER_BURGLAR_QUINN
#define TRAINER_BURGLAR_QUINN 1015
#undef  TRAINER_BURGLAR_RAMON
#define TRAINER_BURGLAR_RAMON 1016
#undef  TRAINER_BURGLAR_DUSTY
#define TRAINER_BURGLAR_DUSTY 1017
#undef  TRAINER_BURGLAR_ARNIE
#define TRAINER_BURGLAR_ARNIE 1018
#undef  TRAINER_BURGLAR_SIMON
#define TRAINER_BURGLAR_SIMON 1019
#undef  TRAINER_BURGLAR_LEWIS
#define TRAINER_BURGLAR_LEWIS 1020
#undef  TRAINER_ENGINEER_BAILY
#define TRAINER_ENGINEER_BAILY 1021
#undef  TRAINER_ENGINEER_BRAXTON
#define TRAINER_ENGINEER_BRAXTON 1022
#undef  TRAINER_ENGINEER_BERNIE
#define TRAINER_ENGINEER_BERNIE 1023
#undef  TRAINER_FISHERMAN_DALE
#define TRAINER_FISHERMAN_DALE 1024
#undef  TRAINER_FISHERMAN_BARNY
#define TRAINER_FISHERMAN_BARNY 1025
#undef  TRAINER_FISHERMAN_NED
#define TRAINER_FISHERMAN_NED 1026
#undef  TRAINER_FISHERMAN_CHIP
#define TRAINER_FISHERMAN_CHIP 1027
#undef  TRAINER_FISHERMAN_HANK
#define TRAINER_FISHERMAN_HANK 1028
#undef  TRAINER_FISHERMAN_ELLIOT
#define TRAINER_FISHERMAN_ELLIOT 1029
#undef  TRAINER_FISHERMAN_RONALD
#define TRAINER_FISHERMAN_RONALD 1030
#undef  TRAINER_FISHERMAN_CLAUDE
#define TRAINER_FISHERMAN_CLAUDE 1031
#undef  TRAINER_FISHERMAN_WADE
#define TRAINER_FISHERMAN_WADE 1032
#undef  TRAINER_FISHERMAN_NOLAN
#define TRAINER_FISHERMAN_NOLAN 1033
#undef  TRAINER_FISHERMAN_ANDREW
#define TRAINER_FISHERMAN_ANDREW 1034
#undef  TRAINER_SWIMMER_MALE_LUIS
#define TRAINER_SWIMMER_MALE_LUIS 1035
#undef  TRAINER_SWIMMER_MALE_RICHARD
#define TRAINER_SWIMMER_MALE_RICHARD 1036
#undef  TRAINER_SWIMMER_MALE_REECE
#define TRAINER_SWIMMER_MALE_REECE 1037
#undef  TRAINER_SWIMMER_MALE_MATTHEW
#define TRAINER_SWIMMER_MALE_MATTHEW 1038
#undef  TRAINER_SWIMMER_MALE_DOUGLAS
#define TRAINER_SWIMMER_MALE_DOUGLAS 1039
#undef  TRAINER_SWIMMER_MALE_DAVID
#define TRAINER_SWIMMER_MALE_DAVID 1040
#undef  TRAINER_SWIMMER_MALE_TONY
#define TRAINER_SWIMMER_MALE_TONY 1041
#undef  TRAINER_SWIMMER_MALE_AXLE
#define TRAINER_SWIMMER_MALE_AXLE 1042
#undef  TRAINER_SWIMMER_MALE_BARRY
#define TRAINER_SWIMMER_MALE_BARRY 1043
#undef  TRAINER_SWIMMER_MALE_DEAN
#define TRAINER_SWIMMER_MALE_DEAN 1044
#undef  TRAINER_SWIMMER_MALE_DARRIN
#define TRAINER_SWIMMER_MALE_DARRIN 1045
#undef  TRAINER_SWIMMER_MALE_SPENCER
#define TRAINER_SWIMMER_MALE_SPENCER 1046
#undef  TRAINER_SWIMMER_MALE_JACK
#define TRAINER_SWIMMER_MALE_JACK 1047
#undef  TRAINER_SWIMMER_MALE_JEROME
#define TRAINER_SWIMMER_MALE_JEROME 1048
#undef  TRAINER_SWIMMER_MALE_ROLAND
#define TRAINER_SWIMMER_MALE_ROLAND 1049
#undef  TRAINER_CUE_BALL_KOJI
#define TRAINER_CUE_BALL_KOJI 1050
#undef  TRAINER_CUE_BALL_LUKE
#define TRAINER_CUE_BALL_LUKE 1051
#undef  TRAINER_CUE_BALL_CAMRON
#define TRAINER_CUE_BALL_CAMRON 1052
#undef  TRAINER_CUE_BALL_RAUL
#define TRAINER_CUE_BALL_RAUL 1053
#undef  TRAINER_CUE_BALL_ISAIAH
#define TRAINER_CUE_BALL_ISAIAH 1054
#undef  TRAINER_CUE_BALL_ZEEK
#define TRAINER_CUE_BALL_ZEEK 1055
#undef  TRAINER_CUE_BALL_JAMAL
#define TRAINER_CUE_BALL_JAMAL 1056
#undef  TRAINER_CUE_BALL_COREY
#define TRAINER_CUE_BALL_COREY 1057
#undef  TRAINER_CUE_BALL_CHASE
#define TRAINER_CUE_BALL_CHASE 1058
#undef  TRAINER_GAMER_HUGO
#define TRAINER_GAMER_HUGO 1059
#undef  TRAINER_GAMER_JASPER
#define TRAINER_GAMER_JASPER 1060
#undef  TRAINER_GAMER_DIRK
#define TRAINER_GAMER_DIRK 1061
#undef  TRAINER_GAMER_DARIAN
#define TRAINER_GAMER_DARIAN 1062
#undef  TRAINER_GAMER_STAN
#define TRAINER_GAMER_STAN 1063
#undef  TRAINER_GAMER_RICH
#define TRAINER_GAMER_RICH 1064
#undef  TRAINER_BEAUTY_BRIDGET
#define TRAINER_BEAUTY_BRIDGET 1065
#undef  TRAINER_BEAUTY_TAMIA
#define TRAINER_BEAUTY_TAMIA 1066
#undef  TRAINER_BEAUTY_LORI
#define TRAINER_BEAUTY_LORI 1067
#undef  TRAINER_BEAUTY_LOLA
#define TRAINER_BEAUTY_LOLA 1068
#undef  TRAINER_BEAUTY_SHEILA
#define TRAINER_BEAUTY_SHEILA 1069
#undef  TRAINER_SWIMMER_FEMALE_TIFFANY
#define TRAINER_SWIMMER_FEMALE_TIFFANY 1070
#undef  TRAINER_SWIMMER_FEMALE_NORA
#define TRAINER_SWIMMER_FEMALE_NORA 1071
#undef  TRAINER_SWIMMER_FEMALE_MELISSA
#define TRAINER_SWIMMER_FEMALE_MELISSA 1072
#undef  TRAINER_BEAUTY_GRACE
#define TRAINER_BEAUTY_GRACE 1073
#undef  TRAINER_BEAUTY_OLIVIA
#define TRAINER_BEAUTY_OLIVIA 1074
#undef  TRAINER_BEAUTY_LAUREN
#define TRAINER_BEAUTY_LAUREN 1075
#undef  TRAINER_SWIMMER_FEMALE_ANYA
#define TRAINER_SWIMMER_FEMALE_ANYA 1076
#undef  TRAINER_SWIMMER_FEMALE_ALICE
#define TRAINER_SWIMMER_FEMALE_ALICE 1077
#undef  TRAINER_SWIMMER_FEMALE_CONNIE
#define TRAINER_SWIMMER_FEMALE_CONNIE 1078
#undef  TRAINER_SWIMMER_FEMALE_SHIRLEY
#define TRAINER_SWIMMER_FEMALE_SHIRLEY 1079
#undef  TRAINER_PSYCHIC_JOHAN
#define TRAINER_PSYCHIC_JOHAN 1080
#undef  TRAINER_PSYCHIC_TYRON
#define TRAINER_PSYCHIC_TYRON 1081
#undef  TRAINER_PSYCHIC_CAMERON
#define TRAINER_PSYCHIC_CAMERON 1082
#undef  TRAINER_PSYCHIC_PRESTON
#define TRAINER_PSYCHIC_PRESTON 1083
#undef  TRAINER_ROCKER_RANDALL
#define TRAINER_ROCKER_RANDALL 1084
#undef  TRAINER_ROCKER_LUCA
#define TRAINER_ROCKER_LUCA 1085
#undef  TRAINER_JUGGLER_DALTON
#define TRAINER_JUGGLER_DALTON 1086
#undef  TRAINER_JUGGLER_NELSON
#define TRAINER_JUGGLER_NELSON 1087
#undef  TRAINER_JUGGLER_KIRK
#define TRAINER_JUGGLER_KIRK 1088
#undef  TRAINER_JUGGLER_SHAWN
#define TRAINER_JUGGLER_SHAWN 1089
#undef  TRAINER_JUGGLER_GREGORY
#define TRAINER_JUGGLER_GREGORY 1090
#undef  TRAINER_JUGGLER_EDWARD
#define TRAINER_JUGGLER_EDWARD 1091
#undef  TRAINER_JUGGLER_KAYDEN
#define TRAINER_JUGGLER_KAYDEN 1092
#undef  TRAINER_JUGGLER_NATE
#define TRAINER_JUGGLER_NATE 1093
#undef  TRAINER_TAMER_PHIL
#define TRAINER_TAMER_PHIL 1094
#undef  TRAINER_TAMER_EDGAR
#define TRAINER_TAMER_EDGAR 1095
#undef  TRAINER_TAMER_JASON
#define TRAINER_TAMER_JASON 1096
#undef  TRAINER_TAMER_COLE
#define TRAINER_TAMER_COLE 1097
#undef  TRAINER_TAMER_VINCENT
#define TRAINER_TAMER_VINCENT 1098
#undef  TRAINER_TAMER_JOHN
#define TRAINER_TAMER_JOHN 1099
#undef  TRAINER_BIRD_KEEPER_SEBASTIAN
#define TRAINER_BIRD_KEEPER_SEBASTIAN 1100
#undef  TRAINER_BIRD_KEEPER_PERRY
#define TRAINER_BIRD_KEEPER_PERRY 1101
#undef  TRAINER_BIRD_KEEPER_ROBERT
#define TRAINER_BIRD_KEEPER_ROBERT 1102
#undef  TRAINER_BIRD_KEEPER_DONALD
#define TRAINER_BIRD_KEEPER_DONALD 1103
#undef  TRAINER_BIRD_KEEPER_BENNY
#define TRAINER_BIRD_KEEPER_BENNY 1104
#undef  TRAINER_BIRD_KEEPER_EDWIN
#define TRAINER_BIRD_KEEPER_EDWIN 1105
#undef  TRAINER_BIRD_KEEPER_CHESTER
#define TRAINER_BIRD_KEEPER_CHESTER 1106
#undef  TRAINER_BIRD_KEEPER_WILTON
#define TRAINER_BIRD_KEEPER_WILTON 1107
#undef  TRAINER_BIRD_KEEPER_RAMIRO
#define TRAINER_BIRD_KEEPER_RAMIRO 1108
#undef  TRAINER_BIRD_KEEPER_JACOB
#define TRAINER_BIRD_KEEPER_JACOB 1109
#undef  TRAINER_BIRD_KEEPER_ROGER
#define TRAINER_BIRD_KEEPER_ROGER 1110
#undef  TRAINER_BIRD_KEEPER_REED
#define TRAINER_BIRD_KEEPER_REED 1111
#undef  TRAINER_BIRD_KEEPER_KEITH
#define TRAINER_BIRD_KEEPER_KEITH 1112
#undef  TRAINER_BIRD_KEEPER_CARTER
#define TRAINER_BIRD_KEEPER_CARTER 1113
#undef  TRAINER_BIRD_KEEPER_MITCH
#define TRAINER_BIRD_KEEPER_MITCH 1114
#undef  TRAINER_BIRD_KEEPER_BECK
#define TRAINER_BIRD_KEEPER_BECK 1115
#undef  TRAINER_BIRD_KEEPER_MARLON
#define TRAINER_BIRD_KEEPER_MARLON 1116
#undef  TRAINER_BLACK_BELT_KOICHI
#define TRAINER_BLACK_BELT_KOICHI 1117
#undef  TRAINER_BLACK_BELT_MIKE
#define TRAINER_BLACK_BELT_MIKE 1118
#undef  TRAINER_BLACK_BELT_HIDEKI
#define TRAINER_BLACK_BELT_HIDEKI 1119
#undef  TRAINER_BLACK_BELT_AARON
#define TRAINER_BLACK_BELT_AARON 1120
#undef  TRAINER_BLACK_BELT_HITOSHI
#define TRAINER_BLACK_BELT_HITOSHI 1121
#undef  TRAINER_BLACK_BELT_ATSUSHI
#define TRAINER_BLACK_BELT_ATSUSHI 1122
#undef  TRAINER_BLACK_BELT_KIYO
#define TRAINER_BLACK_BELT_KIYO 1123
#undef  TRAINER_BLACK_BELT_TAKASHI
#define TRAINER_BLACK_BELT_TAKASHI 1124
#undef  TRAINER_BLACK_BELT_DAISUKE
#define TRAINER_BLACK_BELT_DAISUKE 1125
#undef  TRAINER_RIVAL_OAKS_LAB_SQUIRTLE
#define TRAINER_RIVAL_OAKS_LAB_SQUIRTLE 1126
#undef  TRAINER_RIVAL_OAKS_LAB_BULBASAUR
#define TRAINER_RIVAL_OAKS_LAB_BULBASAUR 1127
#undef  TRAINER_RIVAL_OAKS_LAB_CHARMANDER
#define TRAINER_RIVAL_OAKS_LAB_CHARMANDER 1128
#undef  TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE
#define TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE 1129
#undef  TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR
#define TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR 1130
#undef  TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER
#define TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER 1131
#undef  TRAINER_RIVAL_CERULEAN_SQUIRTLE
#define TRAINER_RIVAL_CERULEAN_SQUIRTLE 1132
#undef  TRAINER_RIVAL_CERULEAN_BULBASAUR
#define TRAINER_RIVAL_CERULEAN_BULBASAUR 1133
#undef  TRAINER_RIVAL_CERULEAN_CHARMANDER
#define TRAINER_RIVAL_CERULEAN_CHARMANDER 1134
#undef  TRAINER_SCIENTIST_TED
#define TRAINER_SCIENTIST_TED 1135
#undef  TRAINER_SCIENTIST_CONNOR
#define TRAINER_SCIENTIST_CONNOR 1136
#undef  TRAINER_SCIENTIST_JERRY
#define TRAINER_SCIENTIST_JERRY 1137
#undef  TRAINER_SCIENTIST_JOSE
#define TRAINER_SCIENTIST_JOSE 1138
#undef  TRAINER_SCIENTIST_RODNEY
#define TRAINER_SCIENTIST_RODNEY 1139
#undef  TRAINER_SCIENTIST_BEAU
#define TRAINER_SCIENTIST_BEAU 1140
#undef  TRAINER_SCIENTIST_TAYLOR
#define TRAINER_SCIENTIST_TAYLOR 1141
#undef  TRAINER_SCIENTIST_JOSHUA
#define TRAINER_SCIENTIST_JOSHUA 1142
#undef  TRAINER_SCIENTIST_PARKER
#define TRAINER_SCIENTIST_PARKER 1143
#undef  TRAINER_SCIENTIST_ED
#define TRAINER_SCIENTIST_ED 1144
#undef  TRAINER_SCIENTIST_TRAVIS
#define TRAINER_SCIENTIST_TRAVIS 1145
#undef  TRAINER_SCIENTIST_BRAYDON
#define TRAINER_SCIENTIST_BRAYDON 1146
#undef  TRAINER_SCIENTIST_IVAN
#define TRAINER_SCIENTIST_IVAN 1147
#undef  TRAINER_BOSS_GIOVANNI
#define TRAINER_BOSS_GIOVANNI 1148
#undef  TRAINER_BOSS_GIOVANNI_2
#define TRAINER_BOSS_GIOVANNI_2 1149
#undef  TRAINER_LEADER_GIOVANNI
#define TRAINER_LEADER_GIOVANNI 1150
#undef  TRAINER_TEAM_ROCKET_GRUNT
#define TRAINER_TEAM_ROCKET_GRUNT 1151
#undef  TRAINER_TEAM_ROCKET_GRUNT_2
#define TRAINER_TEAM_ROCKET_GRUNT_2 1152
#undef  TRAINER_TEAM_ROCKET_GRUNT_3
#define TRAINER_TEAM_ROCKET_GRUNT_3 1153
#undef  TRAINER_TEAM_ROCKET_GRUNT_4
#define TRAINER_TEAM_ROCKET_GRUNT_4 1154
#undef  TRAINER_TEAM_ROCKET_GRUNT_5
#define TRAINER_TEAM_ROCKET_GRUNT_5 1155
#undef  TRAINER_TEAM_ROCKET_GRUNT_6
#define TRAINER_TEAM_ROCKET_GRUNT_6 1156
#undef  TRAINER_TEAM_ROCKET_GRUNT_7
#define TRAINER_TEAM_ROCKET_GRUNT_7 1157
#undef  TRAINER_TEAM_ROCKET_GRUNT_8
#define TRAINER_TEAM_ROCKET_GRUNT_8 1158
#undef  TRAINER_TEAM_ROCKET_GRUNT_9
#define TRAINER_TEAM_ROCKET_GRUNT_9 1159
#undef  TRAINER_TEAM_ROCKET_GRUNT_10
#define TRAINER_TEAM_ROCKET_GRUNT_10 1160
#undef  TRAINER_TEAM_ROCKET_GRUNT_11
#define TRAINER_TEAM_ROCKET_GRUNT_11 1161
#undef  TRAINER_TEAM_ROCKET_GRUNT_12
#define TRAINER_TEAM_ROCKET_GRUNT_12 1162
#undef  TRAINER_TEAM_ROCKET_GRUNT_13
#define TRAINER_TEAM_ROCKET_GRUNT_13 1163
#undef  TRAINER_TEAM_ROCKET_GRUNT_14
#define TRAINER_TEAM_ROCKET_GRUNT_14 1164
#undef  TRAINER_TEAM_ROCKET_GRUNT_15
#define TRAINER_TEAM_ROCKET_GRUNT_15 1165
#undef  TRAINER_TEAM_ROCKET_GRUNT_16
#define TRAINER_TEAM_ROCKET_GRUNT_16 1166
#undef  TRAINER_TEAM_ROCKET_GRUNT_17
#define TRAINER_TEAM_ROCKET_GRUNT_17 1167
#undef  TRAINER_TEAM_ROCKET_GRUNT_18
#define TRAINER_TEAM_ROCKET_GRUNT_18 1168
#undef  TRAINER_TEAM_ROCKET_GRUNT_19
#define TRAINER_TEAM_ROCKET_GRUNT_19 1169
#undef  TRAINER_TEAM_ROCKET_GRUNT_20
#define TRAINER_TEAM_ROCKET_GRUNT_20 1170
#undef  TRAINER_TEAM_ROCKET_GRUNT_21
#define TRAINER_TEAM_ROCKET_GRUNT_21 1171
#undef  TRAINER_TEAM_ROCKET_GRUNT_22
#define TRAINER_TEAM_ROCKET_GRUNT_22 1172
#undef  TRAINER_TEAM_ROCKET_GRUNT_23
#define TRAINER_TEAM_ROCKET_GRUNT_23 1173
#undef  TRAINER_TEAM_ROCKET_GRUNT_24
#define TRAINER_TEAM_ROCKET_GRUNT_24 1174
#undef  TRAINER_TEAM_ROCKET_GRUNT_25
#define TRAINER_TEAM_ROCKET_GRUNT_25 1175
#undef  TRAINER_TEAM_ROCKET_GRUNT_26
#define TRAINER_TEAM_ROCKET_GRUNT_26 1176
#undef  TRAINER_TEAM_ROCKET_GRUNT_27
#define TRAINER_TEAM_ROCKET_GRUNT_27 1177
#undef  TRAINER_TEAM_ROCKET_GRUNT_28
#define TRAINER_TEAM_ROCKET_GRUNT_28 1178
#undef  TRAINER_TEAM_ROCKET_GRUNT_29
#define TRAINER_TEAM_ROCKET_GRUNT_29 1179
#undef  TRAINER_TEAM_ROCKET_GRUNT_30
#define TRAINER_TEAM_ROCKET_GRUNT_30 1180
#undef  TRAINER_TEAM_ROCKET_GRUNT_31
#define TRAINER_TEAM_ROCKET_GRUNT_31 1181
#undef  TRAINER_TEAM_ROCKET_GRUNT_32
#define TRAINER_TEAM_ROCKET_GRUNT_32 1182
#undef  TRAINER_TEAM_ROCKET_GRUNT_33
#define TRAINER_TEAM_ROCKET_GRUNT_33 1183
#undef  TRAINER_TEAM_ROCKET_GRUNT_34
#define TRAINER_TEAM_ROCKET_GRUNT_34 1184
#undef  TRAINER_TEAM_ROCKET_GRUNT_35
#define TRAINER_TEAM_ROCKET_GRUNT_35 1185
#undef  TRAINER_TEAM_ROCKET_GRUNT_36
#define TRAINER_TEAM_ROCKET_GRUNT_36 1186
#undef  TRAINER_TEAM_ROCKET_GRUNT_37
#define TRAINER_TEAM_ROCKET_GRUNT_37 1187
#undef  TRAINER_TEAM_ROCKET_GRUNT_38
#define TRAINER_TEAM_ROCKET_GRUNT_38 1188
#undef  TRAINER_TEAM_ROCKET_GRUNT_39
#define TRAINER_TEAM_ROCKET_GRUNT_39 1189
#undef  TRAINER_TEAM_ROCKET_GRUNT_40
#define TRAINER_TEAM_ROCKET_GRUNT_40 1190
#undef  TRAINER_TEAM_ROCKET_GRUNT_41
#define TRAINER_TEAM_ROCKET_GRUNT_41 1191
#undef  TRAINER_COOLTRAINER_SAMUEL
#define TRAINER_COOLTRAINER_SAMUEL 1192
#undef  TRAINER_COOLTRAINER_GEORGE
#define TRAINER_COOLTRAINER_GEORGE 1193
#undef  TRAINER_COOLTRAINER_COLBY
#define TRAINER_COOLTRAINER_COLBY 1194
#undef  TRAINER_COOLTRAINER_PAUL
#define TRAINER_COOLTRAINER_PAUL 1195
#undef  TRAINER_COOLTRAINER_ROLANDO
#define TRAINER_COOLTRAINER_ROLANDO 1196
#undef  TRAINER_COOLTRAINER_GILBERT
#define TRAINER_COOLTRAINER_GILBERT 1197
#undef  TRAINER_COOLTRAINER_OWEN
#define TRAINER_COOLTRAINER_OWEN 1198
#undef  TRAINER_COOLTRAINER_BERKE
#define TRAINER_COOLTRAINER_BERKE 1199
#undef  TRAINER_COOLTRAINER_YUJI
#define TRAINER_COOLTRAINER_YUJI 1200
#undef  TRAINER_COOLTRAINER_WARREN
#define TRAINER_COOLTRAINER_WARREN 1201
#undef  TRAINER_COOLTRAINER_MARY
#define TRAINER_COOLTRAINER_MARY 1202
#undef  TRAINER_COOLTRAINER_CAROLINE
#define TRAINER_COOLTRAINER_CAROLINE 1203
#undef  TRAINER_COOLTRAINER_ALEXA
#define TRAINER_COOLTRAINER_ALEXA 1204
#undef  TRAINER_COOLTRAINER_SHANNON
#define TRAINER_COOLTRAINER_SHANNON 1205
#undef  TRAINER_COOLTRAINER_NAOMI
#define TRAINER_COOLTRAINER_NAOMI 1206
#undef  TRAINER_COOLTRAINER_BROOKE
#define TRAINER_COOLTRAINER_BROOKE 1207
#undef  TRAINER_COOLTRAINER_AUSTINA
#define TRAINER_COOLTRAINER_AUSTINA 1208
#undef  TRAINER_COOLTRAINER_JULIE
#define TRAINER_COOLTRAINER_JULIE 1209
#undef  TRAINER_ELITE_FOUR_LORELEI
#define TRAINER_ELITE_FOUR_LORELEI 1210
#undef  TRAINER_ELITE_FOUR_BRUNO
#define TRAINER_ELITE_FOUR_BRUNO 1211
#undef  TRAINER_ELITE_FOUR_AGATHA
#define TRAINER_ELITE_FOUR_AGATHA 1212
#undef  TRAINER_ELITE_FOUR_LANCE
#define TRAINER_ELITE_FOUR_LANCE 1213
#undef  TRAINER_LEADER_BROCK
#define TRAINER_LEADER_BROCK 1214
#undef  TRAINER_LEADER_MISTY
#define TRAINER_LEADER_MISTY 1215
#undef  TRAINER_LEADER_LT_SURGE
#define TRAINER_LEADER_LT_SURGE 1216
#undef  TRAINER_LEADER_ERIKA
#define TRAINER_LEADER_ERIKA 1217
#undef  TRAINER_LEADER_KOGA
#define TRAINER_LEADER_KOGA 1218
#undef  TRAINER_LEADER_BLAINE
#define TRAINER_LEADER_BLAINE 1219
#undef  TRAINER_LEADER_SABRINA
#define TRAINER_LEADER_SABRINA 1220
#undef  TRAINER_GENTLEMAN_THOMAS
#define TRAINER_GENTLEMAN_THOMAS 1221
#undef  TRAINER_GENTLEMAN_ARTHUR
#define TRAINER_GENTLEMAN_ARTHUR 1222
#undef  TRAINER_GENTLEMAN_TUCKER
#define TRAINER_GENTLEMAN_TUCKER 1223
#undef  TRAINER_GENTLEMAN_NORTON
#define TRAINER_GENTLEMAN_NORTON 1224
#undef  TRAINER_GENTLEMAN_WALTER
#define TRAINER_GENTLEMAN_WALTER 1225
#undef  TRAINER_RIVAL_SS_ANNE_SQUIRTLE
#define TRAINER_RIVAL_SS_ANNE_SQUIRTLE 1226
#undef  TRAINER_RIVAL_SS_ANNE_BULBASAUR
#define TRAINER_RIVAL_SS_ANNE_BULBASAUR 1227
#undef  TRAINER_RIVAL_SS_ANNE_CHARMANDER
#define TRAINER_RIVAL_SS_ANNE_CHARMANDER 1228
#undef  TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE
#define TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE 1229
#undef  TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR
#define TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR 1230
#undef  TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER
#define TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER 1231
#undef  TRAINER_RIVAL_SILPH_SQUIRTLE
#define TRAINER_RIVAL_SILPH_SQUIRTLE 1232
#undef  TRAINER_RIVAL_SILPH_BULBASAUR
#define TRAINER_RIVAL_SILPH_BULBASAUR 1233
#undef  TRAINER_RIVAL_SILPH_CHARMANDER
#define TRAINER_RIVAL_SILPH_CHARMANDER 1234
#undef  TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE
#define TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE 1235
#undef  TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR
#define TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR 1236
#undef  TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER
#define TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER 1237
#undef  TRAINER_CHAMPION_FIRST_SQUIRTLE
#define TRAINER_CHAMPION_FIRST_SQUIRTLE 1238
#undef  TRAINER_CHAMPION_FIRST_BULBASAUR
#define TRAINER_CHAMPION_FIRST_BULBASAUR 1239
#undef  TRAINER_CHAMPION_FIRST_CHARMANDER
#define TRAINER_CHAMPION_FIRST_CHARMANDER 1240
#undef  TRAINER_CHANNELER_PATRICIA
#define TRAINER_CHANNELER_PATRICIA 1241
#undef  TRAINER_CHANNELER_CARLY
#define TRAINER_CHANNELER_CARLY 1242
#undef  TRAINER_CHANNELER_HOPE
#define TRAINER_CHANNELER_HOPE 1243
#undef  TRAINER_CHANNELER_PAULA
#define TRAINER_CHANNELER_PAULA 1244
#undef  TRAINER_CHANNELER_LAUREL
#define TRAINER_CHANNELER_LAUREL 1245
#undef  TRAINER_CHANNELER_JODY
#define TRAINER_CHANNELER_JODY 1246
#undef  TRAINER_CHANNELER_TAMMY
#define TRAINER_CHANNELER_TAMMY 1247
#undef  TRAINER_CHANNELER_RUTH
#define TRAINER_CHANNELER_RUTH 1248
#undef  TRAINER_CHANNELER_KARINA
#define TRAINER_CHANNELER_KARINA 1249
#undef  TRAINER_CHANNELER_JANAE
#define TRAINER_CHANNELER_JANAE 1250
#undef  TRAINER_CHANNELER_ANGELICA
#define TRAINER_CHANNELER_ANGELICA 1251
#undef  TRAINER_CHANNELER_EMILIA
#define TRAINER_CHANNELER_EMILIA 1252
#undef  TRAINER_CHANNELER_JENNIFER
#define TRAINER_CHANNELER_JENNIFER 1253
#undef  TRAINER_CHANNELER_AMANDA
#define TRAINER_CHANNELER_AMANDA 1254
#undef  TRAINER_CHANNELER_STACY
#define TRAINER_CHANNELER_STACY 1255
#undef  TRAINER_CHANNELER_TASHA
#define TRAINER_CHANNELER_TASHA 1256
#undef  TRAINER_HIKER_JEREMY
#define TRAINER_HIKER_JEREMY 1257
#undef  TRAINER_PICNICKER_ALMA
#define TRAINER_PICNICKER_ALMA 1258
#undef  TRAINER_PICNICKER_SUSIE
#define TRAINER_PICNICKER_SUSIE 1259
#undef  TRAINER_PICNICKER_VALERIE
#define TRAINER_PICNICKER_VALERIE 1260
#undef  TRAINER_PICNICKER_GWEN
#define TRAINER_PICNICKER_GWEN 1261
#undef  TRAINER_BIKER_VIRGIL
#define TRAINER_BIKER_VIRGIL 1262
#undef  TRAINER_CAMPER_FLINT
#define TRAINER_CAMPER_FLINT 1263
#undef  TRAINER_PICNICKER_MISSY
#define TRAINER_PICNICKER_MISSY 1264
#undef  TRAINER_PICNICKER_IRENE
#define TRAINER_PICNICKER_IRENE 1265
#undef  TRAINER_PICNICKER_DANA
#define TRAINER_PICNICKER_DANA 1266
#undef  TRAINER_PICNICKER_ARIANA
#define TRAINER_PICNICKER_ARIANA 1267
#undef  TRAINER_PICNICKER_LEAH
#define TRAINER_PICNICKER_LEAH 1268
#undef  TRAINER_CAMPER_JUSTIN
#define TRAINER_CAMPER_JUSTIN 1269
#undef  TRAINER_PICNICKER_YAZMIN
#define TRAINER_PICNICKER_YAZMIN 1270
#undef  TRAINER_PICNICKER_KINDRA
#define TRAINER_PICNICKER_KINDRA 1271
#undef  TRAINER_PICNICKER_BECKY
#define TRAINER_PICNICKER_BECKY 1272
#undef  TRAINER_PICNICKER_CELIA
#define TRAINER_PICNICKER_CELIA 1273
#undef  TRAINER_GENTLEMAN_BROOKS
#define TRAINER_GENTLEMAN_BROOKS 1274
#undef  TRAINER_GENTLEMAN_LAMAR
#define TRAINER_GENTLEMAN_LAMAR 1275
#undef  TRAINER_TWINS_ELI_ANNE
#define TRAINER_TWINS_ELI_ANNE 1276
#undef  TRAINER_COOL_COUPLE_RAY_TYRA
#define TRAINER_COOL_COUPLE_RAY_TYRA 1277
#undef  TRAINER_YOUNG_COUPLE_GIA_JES
#define TRAINER_YOUNG_COUPLE_GIA_JES 1278
#undef  TRAINER_TWINS_KIRI_JAN
#define TRAINER_TWINS_KIRI_JAN 1279
#undef  TRAINER_CRUSH_KIN_RON_MYA
#define TRAINER_CRUSH_KIN_RON_MYA 1280
#undef  TRAINER_YOUNG_COUPLE_LEA_JED
#define TRAINER_YOUNG_COUPLE_LEA_JED 1281
#undef  TRAINER_SIS_AND_BRO_LIA_LUC
#define TRAINER_SIS_AND_BRO_LIA_LUC 1282
#undef  TRAINER_SIS_AND_BRO_LIL_IAN
#define TRAINER_SIS_AND_BRO_LIL_IAN 1283
#undef  TRAINER_YOUNGSTER_BEN_3
#define TRAINER_YOUNGSTER_BEN_3 1284
#undef  TRAINER_YOUNGSTER_BEN_4
#define TRAINER_YOUNGSTER_BEN_4 1285
#undef  TRAINER_YOUNGSTER_CHAD_2
#define TRAINER_YOUNGSTER_CHAD_2 1286
#undef  TRAINER_LASS_RELI_2
#define TRAINER_LASS_RELI_2 1287
#undef  TRAINER_LASS_RELI_3
#define TRAINER_LASS_RELI_3 1288
#undef  TRAINER_YOUNGSTER_TIMMY_2
#define TRAINER_YOUNGSTER_TIMMY_2 1289
#undef  TRAINER_YOUNGSTER_TIMMY_3
#define TRAINER_YOUNGSTER_TIMMY_3 1290
#undef  TRAINER_YOUNGSTER_TIMMY_4
#define TRAINER_YOUNGSTER_TIMMY_4 1291
#undef  TRAINER_YOUNGSTER_CHAD_3
#define TRAINER_YOUNGSTER_CHAD_3 1292
#undef  TRAINER_LASS_JANICE_2
#define TRAINER_LASS_JANICE_2 1293
#undef  TRAINER_LASS_JANICE_3
#define TRAINER_LASS_JANICE_3 1294
#undef  TRAINER_YOUNGSTER_CHAD_4
#define TRAINER_YOUNGSTER_CHAD_4 1295
#undef  TRAINER_HIKER_FRANKLIN_2
#define TRAINER_HIKER_FRANKLIN_2 1296
#undef  TRAINER_PKMN_PROF_PROF_OAK
#define TRAINER_PKMN_PROF_PROF_OAK 1297
#undef  TRAINER_TEAM_ROCKET_GRUNT_42
#define TRAINER_TEAM_ROCKET_GRUNT_42 1298
#undef  TRAINER_PSYCHIC_JACLYN
#define TRAINER_PSYCHIC_JACLYN 1299
#undef  TRAINER_CRUSH_GIRL_SHARON
#define TRAINER_CRUSH_GIRL_SHARON 1300
#undef  TRAINER_TUBER_AMIRA
#define TRAINER_TUBER_AMIRA 1301
#undef  TRAINER_PKMN_BREEDER_ALIZE
#define TRAINER_PKMN_BREEDER_ALIZE 1302
#undef  TRAINER_PKMN_RANGER_NICOLAS
#define TRAINER_PKMN_RANGER_NICOLAS 1303
#undef  TRAINER_PKMN_RANGER_MADELINE
#define TRAINER_PKMN_RANGER_MADELINE 1304
#undef  TRAINER_AROMA_LADY_NIKKI
#define TRAINER_AROMA_LADY_NIKKI 1305
#undef  TRAINER_RUIN_MANIAC_STANLY
#define TRAINER_RUIN_MANIAC_STANLY 1306
#undef  TRAINER_LADY_JACKI
#define TRAINER_LADY_JACKI 1307
#undef  TRAINER_PAINTER_DAISY
#define TRAINER_PAINTER_DAISY 1308
#undef  TRAINER_BIKER_GOON
#define TRAINER_BIKER_GOON 1309
#undef  TRAINER_BIKER_GOON_2
#define TRAINER_BIKER_GOON_2 1310
#undef  TRAINER_BIKER_GOON_3
#define TRAINER_BIKER_GOON_3 1311
#undef  TRAINER_BUG_CATCHER_ANTHONY
#define TRAINER_BUG_CATCHER_ANTHONY 1312
#undef  TRAINER_BUG_CATCHER_CHARLIE
#define TRAINER_BUG_CATCHER_CHARLIE 1313
#undef  TRAINER_TWINS_ELI_ANNE_2
#define TRAINER_TWINS_ELI_ANNE_2 1314
#undef  TRAINER_YOUNGSTER_JOHNSON
#define TRAINER_YOUNGSTER_JOHNSON 1315
#undef  TRAINER_BIKER_RICARDO
#define TRAINER_BIKER_RICARDO 1316
#undef  TRAINER_BIKER_JAREN
#define TRAINER_BIKER_JAREN 1317
#undef  TRAINER_TEAM_ROCKET_GRUNT_43
#define TRAINER_TEAM_ROCKET_GRUNT_43 1318
#undef  TRAINER_TEAM_ROCKET_GRUNT_44
#define TRAINER_TEAM_ROCKET_GRUNT_44 1319
#undef  TRAINER_TEAM_ROCKET_GRUNT_45
#define TRAINER_TEAM_ROCKET_GRUNT_45 1320
#undef  TRAINER_TEAM_ROCKET_GRUNT_46
#define TRAINER_TEAM_ROCKET_GRUNT_46 1321
#undef  TRAINER_TEAM_ROCKET_GRUNT_47
#define TRAINER_TEAM_ROCKET_GRUNT_47 1322
#undef  TRAINER_TEAM_ROCKET_GRUNT_48
#define TRAINER_TEAM_ROCKET_GRUNT_48 1323
#undef  TRAINER_TEAM_ROCKET_ADMIN
#define TRAINER_TEAM_ROCKET_ADMIN 1324
#undef  TRAINER_TEAM_ROCKET_ADMIN_2
#define TRAINER_TEAM_ROCKET_ADMIN_2 1325
#undef  TRAINER_SCIENTIST_GIDEON
#define TRAINER_SCIENTIST_GIDEON 1326
#undef  TRAINER_SWIMMER_FEMALE_AMARA
#define TRAINER_SWIMMER_FEMALE_AMARA 1327
#undef  TRAINER_SWIMMER_FEMALE_MARIA
#define TRAINER_SWIMMER_FEMALE_MARIA 1328
#undef  TRAINER_SWIMMER_FEMALE_ABIGAIL
#define TRAINER_SWIMMER_FEMALE_ABIGAIL 1329
#undef  TRAINER_SWIMMER_MALE_FINN
#define TRAINER_SWIMMER_MALE_FINN 1330
#undef  TRAINER_SWIMMER_MALE_GARRETT
#define TRAINER_SWIMMER_MALE_GARRETT 1331
#undef  TRAINER_FISHERMAN_TOMMY
#define TRAINER_FISHERMAN_TOMMY 1332
#undef  TRAINER_CRUSH_GIRL_TANYA
#define TRAINER_CRUSH_GIRL_TANYA 1333
#undef  TRAINER_BLACK_BELT_SHEA
#define TRAINER_BLACK_BELT_SHEA 1334
#undef  TRAINER_BLACK_BELT_HUGH
#define TRAINER_BLACK_BELT_HUGH 1335
#undef  TRAINER_CAMPER_BRYCE
#define TRAINER_CAMPER_BRYCE 1336
#undef  TRAINER_PICNICKER_CLAIRE
#define TRAINER_PICNICKER_CLAIRE 1337
#undef  TRAINER_CRUSH_KIN_MIK_KIA
#define TRAINER_CRUSH_KIN_MIK_KIA 1338
#undef  TRAINER_AROMA_LADY_VIOLET
#define TRAINER_AROMA_LADY_VIOLET 1339
#undef  TRAINER_TUBER_ALEXIS
#define TRAINER_TUBER_ALEXIS 1340
#undef  TRAINER_TWINS_JOY_MEG
#define TRAINER_TWINS_JOY_MEG 1341
#undef  TRAINER_SWIMMER_FEMALE_TISHA
#define TRAINER_SWIMMER_FEMALE_TISHA 1342
#undef  TRAINER_PAINTER_CELINA
#define TRAINER_PAINTER_CELINA 1343
#undef  TRAINER_PAINTER_RAYNA
#define TRAINER_PAINTER_RAYNA 1344
#undef  TRAINER_LADY_GILLIAN
#define TRAINER_LADY_GILLIAN 1345
#undef  TRAINER_YOUNGSTER_DESTIN
#define TRAINER_YOUNGSTER_DESTIN 1346
#undef  TRAINER_SWIMMER_MALE_TOBY
#define TRAINER_SWIMMER_MALE_TOBY 1347
#undef  TRAINER_TEAM_ROCKET_GRUNT_49
#define TRAINER_TEAM_ROCKET_GRUNT_49 1348
#undef  TRAINER_TEAM_ROCKET_GRUNT_50
#define TRAINER_TEAM_ROCKET_GRUNT_50 1349
#undef  TRAINER_TEAM_ROCKET_GRUNT_51
#define TRAINER_TEAM_ROCKET_GRUNT_51 1350
#undef  TRAINER_BIRD_KEEPER_MILO
#define TRAINER_BIRD_KEEPER_MILO 1351
#undef  TRAINER_BIRD_KEEPER_CHAZ
#define TRAINER_BIRD_KEEPER_CHAZ 1352
#undef  TRAINER_BIRD_KEEPER_HAROLD
#define TRAINER_BIRD_KEEPER_HAROLD 1353
#undef  TRAINER_FISHERMAN_TYLOR
#define TRAINER_FISHERMAN_TYLOR 1354
#undef  TRAINER_SWIMMER_MALE_MYMO
#define TRAINER_SWIMMER_MALE_MYMO 1355
#undef  TRAINER_SWIMMER_FEMALE_NICOLE
#define TRAINER_SWIMMER_FEMALE_NICOLE 1356
#undef  TRAINER_SIS_AND_BRO_AVA_GEB
#define TRAINER_SIS_AND_BRO_AVA_GEB 1357
#undef  TRAINER_AROMA_LADY_ROSE
#define TRAINER_AROMA_LADY_ROSE 1358
#undef  TRAINER_SWIMMER_MALE_SAMIR
#define TRAINER_SWIMMER_MALE_SAMIR 1359
#undef  TRAINER_SWIMMER_FEMALE_DENISE
#define TRAINER_SWIMMER_FEMALE_DENISE 1360
#undef  TRAINER_TWINS_MIU_MIA
#define TRAINER_TWINS_MIU_MIA 1361
#undef  TRAINER_HIKER_EARL
#define TRAINER_HIKER_EARL 1362
#undef  TRAINER_RUIN_MANIAC_FOSTER
#define TRAINER_RUIN_MANIAC_FOSTER 1363
#undef  TRAINER_RUIN_MANIAC_LARRY
#define TRAINER_RUIN_MANIAC_LARRY 1364
#undef  TRAINER_HIKER_DARYL
#define TRAINER_HIKER_DARYL 1365
#undef  TRAINER_POKEMANIAC_HECTOR
#define TRAINER_POKEMANIAC_HECTOR 1366
#undef  TRAINER_PSYCHIC_DARIO
#define TRAINER_PSYCHIC_DARIO 1367
#undef  TRAINER_PSYCHIC_RODETTE
#define TRAINER_PSYCHIC_RODETTE 1368
#undef  TRAINER_AROMA_LADY_MIAH
#define TRAINER_AROMA_LADY_MIAH 1369
#undef  TRAINER_YOUNG_COUPLE_EVE_JON
#define TRAINER_YOUNG_COUPLE_EVE_JON 1370
#undef  TRAINER_JUGGLER_MASON
#define TRAINER_JUGGLER_MASON 1371
#undef  TRAINER_CRUSH_GIRL_CYNDY
#define TRAINER_CRUSH_GIRL_CYNDY 1372
#undef  TRAINER_CRUSH_GIRL_JOCELYN
#define TRAINER_CRUSH_GIRL_JOCELYN 1373
#undef  TRAINER_TAMER_EVAN
#define TRAINER_TAMER_EVAN 1374
#undef  TRAINER_POKEMANIAC_MARK_2
#define TRAINER_POKEMANIAC_MARK_2 1375
#undef  TRAINER_PKMN_RANGER_LOGAN
#define TRAINER_PKMN_RANGER_LOGAN 1376
#undef  TRAINER_PKMN_RANGER_JACKSON
#define TRAINER_PKMN_RANGER_JACKSON 1377
#undef  TRAINER_PKMN_RANGER_BETH
#define TRAINER_PKMN_RANGER_BETH 1378
#undef  TRAINER_PKMN_RANGER_KATELYN
#define TRAINER_PKMN_RANGER_KATELYN 1379
#undef  TRAINER_COOLTRAINER_LEROY
#define TRAINER_COOLTRAINER_LEROY 1380
#undef  TRAINER_COOLTRAINER_MICHELLE
#define TRAINER_COOLTRAINER_MICHELLE 1381
#undef  TRAINER_COOL_COUPLE_LEX_NYA
#define TRAINER_COOL_COUPLE_LEX_NYA 1382
#undef  TRAINER_RUIN_MANIAC_BRANDON
#define TRAINER_RUIN_MANIAC_BRANDON 1383
#undef  TRAINER_RUIN_MANIAC_BENJAMIN
#define TRAINER_RUIN_MANIAC_BENJAMIN 1384
#undef  TRAINER_PAINTER_EDNA
#define TRAINER_PAINTER_EDNA 1385
#undef  TRAINER_GENTLEMAN_CLIFFORD
#define TRAINER_GENTLEMAN_CLIFFORD 1386
#undef  TRAINER_LADY_SELPHY
#define TRAINER_LADY_SELPHY 1387
#undef  TRAINER_RUIN_MANIAC_LAWSON
#define TRAINER_RUIN_MANIAC_LAWSON 1388
#undef  TRAINER_PSYCHIC_LAURA
#define TRAINER_PSYCHIC_LAURA 1389
#undef  TRAINER_PKMN_BREEDER_BETHANY
#define TRAINER_PKMN_BREEDER_BETHANY 1390
#undef  TRAINER_PKMN_BREEDER_ALLISON
#define TRAINER_PKMN_BREEDER_ALLISON 1391
#undef  TRAINER_BUG_CATCHER_GARRET
#define TRAINER_BUG_CATCHER_GARRET 1392
#undef  TRAINER_BUG_CATCHER_JONAH
#define TRAINER_BUG_CATCHER_JONAH 1393
#undef  TRAINER_BUG_CATCHER_VANCE
#define TRAINER_BUG_CATCHER_VANCE 1394
#undef  TRAINER_YOUNGSTER_NASH
#define TRAINER_YOUNGSTER_NASH 1395
#undef  TRAINER_YOUNGSTER_CORDELL
#define TRAINER_YOUNGSTER_CORDELL 1396
#undef  TRAINER_LASS_DALIA
#define TRAINER_LASS_DALIA 1397
#undef  TRAINER_LASS_JOANA
#define TRAINER_LASS_JOANA 1398
#undef  TRAINER_CAMPER_RILEY
#define TRAINER_CAMPER_RILEY 1399
#undef  TRAINER_PICNICKER_MARCY
#define TRAINER_PICNICKER_MARCY 1400
#undef  TRAINER_RUIN_MANIAC_LAYTON
#define TRAINER_RUIN_MANIAC_LAYTON 1401
#undef  TRAINER_PICNICKER_KELSEY_2
#define TRAINER_PICNICKER_KELSEY_2 1402
#undef  TRAINER_PICNICKER_KELSEY_3
#define TRAINER_PICNICKER_KELSEY_3 1403
#undef  TRAINER_PICNICKER_KELSEY_4
#define TRAINER_PICNICKER_KELSEY_4 1404
#undef  TRAINER_CAMPER_RICKY_2
#define TRAINER_CAMPER_RICKY_2 1405
#undef  TRAINER_CAMPER_RICKY_3
#define TRAINER_CAMPER_RICKY_3 1406
#undef  TRAINER_CAMPER_RICKY_4
#define TRAINER_CAMPER_RICKY_4 1407
#undef  TRAINER_CAMPER_JEFF_2
#define TRAINER_CAMPER_JEFF_2 1408
#undef  TRAINER_CAMPER_JEFF_3
#define TRAINER_CAMPER_JEFF_3 1409
#undef  TRAINER_CAMPER_JEFF_4
#define TRAINER_CAMPER_JEFF_4 1410
#undef  TRAINER_PICNICKER_ISABELLE_2
#define TRAINER_PICNICKER_ISABELLE_2 1411
#undef  TRAINER_PICNICKER_ISABELLE_3
#define TRAINER_PICNICKER_ISABELLE_3 1412
#undef  TRAINER_PICNICKER_ISABELLE_4
#define TRAINER_PICNICKER_ISABELLE_4 1413
#undef  TRAINER_YOUNGSTER_YASU_2
#define TRAINER_YOUNGSTER_YASU_2 1414
#undef  TRAINER_YOUNGSTER_YASU_3
#define TRAINER_YOUNGSTER_YASU_3 1415
#undef  TRAINER_ENGINEER_BERNIE_2
#define TRAINER_ENGINEER_BERNIE_2 1416
#undef  TRAINER_GAMER_DARIAN_2
#define TRAINER_GAMER_DARIAN_2 1417
#undef  TRAINER_CAMPER_CHRIS_2
#define TRAINER_CAMPER_CHRIS_2 1418
#undef  TRAINER_CAMPER_CHRIS_3
#define TRAINER_CAMPER_CHRIS_3 1419
#undef  TRAINER_CAMPER_CHRIS_4
#define TRAINER_CAMPER_CHRIS_4 1420
#undef  TRAINER_PICNICKER_ALICIA_2
#define TRAINER_PICNICKER_ALICIA_2 1421
#undef  TRAINER_PICNICKER_ALICIA_3
#define TRAINER_PICNICKER_ALICIA_3 1422
#undef  TRAINER_PICNICKER_ALICIA_4
#define TRAINER_PICNICKER_ALICIA_4 1423
#undef  TRAINER_HIKER_JEREMY_2
#define TRAINER_HIKER_JEREMY_2 1424
#undef  TRAINER_POKEMANIAC_MARK_3
#define TRAINER_POKEMANIAC_MARK_3 1425
#undef  TRAINER_POKEMANIAC_HERMAN_2
#define TRAINER_POKEMANIAC_HERMAN_2 1426
#undef  TRAINER_POKEMANIAC_HERMAN_3
#define TRAINER_POKEMANIAC_HERMAN_3 1427
#undef  TRAINER_HIKER_TRENT_2
#define TRAINER_HIKER_TRENT_2 1428
#undef  TRAINER_LASS_MEGAN_2
#define TRAINER_LASS_MEGAN_2 1429
#undef  TRAINER_LASS_MEGAN_3
#define TRAINER_LASS_MEGAN_3 1430
#undef  TRAINER_SUPER_NERD_GLENN_2
#define TRAINER_SUPER_NERD_GLENN_2 1431
#undef  TRAINER_GAMER_RICH_2
#define TRAINER_GAMER_RICH_2 1432
#undef  TRAINER_BIKER_JAREN_2
#define TRAINER_BIKER_JAREN_2 1433
#undef  TRAINER_FISHERMAN_ELLIOT_2
#define TRAINER_FISHERMAN_ELLIOT_2 1434
#undef  TRAINER_ROCKER_LUCA_2
#define TRAINER_ROCKER_LUCA_2 1435
#undef  TRAINER_BEAUTY_SHEILA_2
#define TRAINER_BEAUTY_SHEILA_2 1436
#undef  TRAINER_BIRD_KEEPER_ROBERT_2
#define TRAINER_BIRD_KEEPER_ROBERT_2 1437
#undef  TRAINER_BIRD_KEEPER_ROBERT_3
#define TRAINER_BIRD_KEEPER_ROBERT_3 1438
#undef  TRAINER_PICNICKER_SUSIE_2
#define TRAINER_PICNICKER_SUSIE_2 1439
#undef  TRAINER_PICNICKER_SUSIE_3
#define TRAINER_PICNICKER_SUSIE_3 1440
#undef  TRAINER_PICNICKER_SUSIE_4
#define TRAINER_PICNICKER_SUSIE_4 1441
#undef  TRAINER_BIKER_LUKAS_2
#define TRAINER_BIKER_LUKAS_2 1442
#undef  TRAINER_BIRD_KEEPER_BENNY_2
#define TRAINER_BIRD_KEEPER_BENNY_2 1443
#undef  TRAINER_BIRD_KEEPER_BENNY_3
#define TRAINER_BIRD_KEEPER_BENNY_3 1444
#undef  TRAINER_BIRD_KEEPER_MARLON_2
#define TRAINER_BIRD_KEEPER_MARLON_2 1445
#undef  TRAINER_BIRD_KEEPER_MARLON_3
#define TRAINER_BIRD_KEEPER_MARLON_3 1446
#undef  TRAINER_BEAUTY_GRACE_2
#define TRAINER_BEAUTY_GRACE_2 1447
#undef  TRAINER_BIRD_KEEPER_CHESTER_2
#define TRAINER_BIRD_KEEPER_CHESTER_2 1448
#undef  TRAINER_BIRD_KEEPER_CHESTER_3
#define TRAINER_BIRD_KEEPER_CHESTER_3 1449
#undef  TRAINER_PICNICKER_BECKY_2
#define TRAINER_PICNICKER_BECKY_2 1450
#undef  TRAINER_PICNICKER_BECKY_3
#define TRAINER_PICNICKER_BECKY_3 1451
#undef  TRAINER_PICNICKER_BECKY_4
#define TRAINER_PICNICKER_BECKY_4 1452
#undef  TRAINER_CRUSH_KIN_RON_MYA_2
#define TRAINER_CRUSH_KIN_RON_MYA_2 1453
#undef  TRAINER_CRUSH_KIN_RON_MYA_3
#define TRAINER_CRUSH_KIN_RON_MYA_3 1454
#undef  TRAINER_CRUSH_KIN_RON_MYA_4
#define TRAINER_CRUSH_KIN_RON_MYA_4 1455
#undef  TRAINER_BIKER_RUBEN_2
#define TRAINER_BIKER_RUBEN_2 1456
#undef  TRAINER_CUE_BALL_CAMRON_2
#define TRAINER_CUE_BALL_CAMRON_2 1457
#undef  TRAINER_BIKER_JAXON_2
#define TRAINER_BIKER_JAXON_2 1458
#undef  TRAINER_CUE_BALL_ISAIAH_2
#define TRAINER_CUE_BALL_ISAIAH_2 1459
#undef  TRAINER_CUE_BALL_COREY_2
#define TRAINER_CUE_BALL_COREY_2 1460
#undef  TRAINER_BIRD_KEEPER_JACOB_2
#define TRAINER_BIRD_KEEPER_JACOB_2 1461
#undef  TRAINER_BIRD_KEEPER_JACOB_3
#define TRAINER_BIRD_KEEPER_JACOB_3 1462
#undef  TRAINER_SWIMMER_FEMALE_ALICE_2
#define TRAINER_SWIMMER_FEMALE_ALICE_2 1463
#undef  TRAINER_SWIMMER_MALE_DARRIN_2
#define TRAINER_SWIMMER_MALE_DARRIN_2 1464
#undef  TRAINER_PICNICKER_MISSY_2
#define TRAINER_PICNICKER_MISSY_2 1465
#undef  TRAINER_PICNICKER_MISSY_3
#define TRAINER_PICNICKER_MISSY_3 1466
#undef  TRAINER_FISHERMAN_WADE_2
#define TRAINER_FISHERMAN_WADE_2 1467
#undef  TRAINER_SWIMMER_MALE_JACK_2
#define TRAINER_SWIMMER_MALE_JACK_2 1468
#undef  TRAINER_SIS_AND_BRO_LIL_IAN_2
#define TRAINER_SIS_AND_BRO_LIL_IAN_2 1469
#undef  TRAINER_SIS_AND_BRO_LIL_IAN_3
#define TRAINER_SIS_AND_BRO_LIL_IAN_3 1470
#undef  TRAINER_SWIMMER_MALE_FINN_2
#define TRAINER_SWIMMER_MALE_FINN_2 1471
#undef  TRAINER_CRUSH_GIRL_SHARON_2
#define TRAINER_CRUSH_GIRL_SHARON_2 1472
#undef  TRAINER_CRUSH_GIRL_SHARON_3
#define TRAINER_CRUSH_GIRL_SHARON_3 1473
#undef  TRAINER_CRUSH_GIRL_TANYA_2
#define TRAINER_CRUSH_GIRL_TANYA_2 1474
#undef  TRAINER_CRUSH_GIRL_TANYA_3
#define TRAINER_CRUSH_GIRL_TANYA_3 1475
#undef  TRAINER_BLACK_BELT_SHEA_2
#define TRAINER_BLACK_BELT_SHEA_2 1476
#undef  TRAINER_BLACK_BELT_SHEA_3
#define TRAINER_BLACK_BELT_SHEA_3 1477
#undef  TRAINER_BLACK_BELT_HUGH_2
#define TRAINER_BLACK_BELT_HUGH_2 1478
#undef  TRAINER_BLACK_BELT_HUGH_3
#define TRAINER_BLACK_BELT_HUGH_3 1479
#undef  TRAINER_CRUSH_KIN_MIK_KIA_2
#define TRAINER_CRUSH_KIN_MIK_KIA_2 1480
#undef  TRAINER_CRUSH_KIN_MIK_KIA_3
#define TRAINER_CRUSH_KIN_MIK_KIA_3 1481
#undef  TRAINER_TUBER_AMIRA_2
#define TRAINER_TUBER_AMIRA_2 1482
#undef  TRAINER_TWINS_JOY_MEG_2
#define TRAINER_TWINS_JOY_MEG_2 1483
#undef  TRAINER_PAINTER_RAYNA_2
#define TRAINER_PAINTER_RAYNA_2 1484
#undef  TRAINER_YOUNGSTER_DESTIN_2
#define TRAINER_YOUNGSTER_DESTIN_2 1485
#undef  TRAINER_PKMN_BREEDER_ALIZE_2
#define TRAINER_PKMN_BREEDER_ALIZE_2 1486
#undef  TRAINER_YOUNG_COUPLE_GIA_JES_2
#define TRAINER_YOUNG_COUPLE_GIA_JES_2 1487
#undef  TRAINER_YOUNG_COUPLE_GIA_JES_3
#define TRAINER_YOUNG_COUPLE_GIA_JES_3 1488
#undef  TRAINER_BIRD_KEEPER_MILO_2
#define TRAINER_BIRD_KEEPER_MILO_2 1489
#undef  TRAINER_BIRD_KEEPER_CHAZ_2
#define TRAINER_BIRD_KEEPER_CHAZ_2 1490
#undef  TRAINER_BIRD_KEEPER_HAROLD_2
#define TRAINER_BIRD_KEEPER_HAROLD_2 1491
#undef  TRAINER_SWIMMER_FEMALE_NICOLE_2
#define TRAINER_SWIMMER_FEMALE_NICOLE_2 1492
#undef  TRAINER_PSYCHIC_JACLYN_2
#define TRAINER_PSYCHIC_JACLYN_2 1493
#undef  TRAINER_SWIMMER_MALE_SAMIR_2
#define TRAINER_SWIMMER_MALE_SAMIR_2 1494
#undef  TRAINER_HIKER_EARL_2
#define TRAINER_HIKER_EARL_2 1495
#undef  TRAINER_RUIN_MANIAC_LARRY_2
#define TRAINER_RUIN_MANIAC_LARRY_2 1496
#undef  TRAINER_POKEMANIAC_HECTOR_2
#define TRAINER_POKEMANIAC_HECTOR_2 1497
#undef  TRAINER_PSYCHIC_DARIO_2
#define TRAINER_PSYCHIC_DARIO_2 1498
#undef  TRAINER_PSYCHIC_RODETTE_2
#define TRAINER_PSYCHIC_RODETTE_2 1499
#undef  TRAINER_JUGGLER_MASON_2
#define TRAINER_JUGGLER_MASON_2 1500
#undef  TRAINER_PKMN_RANGER_NICOLAS_2
#define TRAINER_PKMN_RANGER_NICOLAS_2 1501
#undef  TRAINER_PKMN_RANGER_MADELINE_2
#define TRAINER_PKMN_RANGER_MADELINE_2 1502
#undef  TRAINER_CRUSH_GIRL_CYNDY_2
#define TRAINER_CRUSH_GIRL_CYNDY_2 1503
#undef  TRAINER_TAMER_EVAN_2
#define TRAINER_TAMER_EVAN_2 1504
#undef  TRAINER_PKMN_RANGER_JACKSON_2
#define TRAINER_PKMN_RANGER_JACKSON_2 1505
#undef  TRAINER_PKMN_RANGER_KATELYN_2
#define TRAINER_PKMN_RANGER_KATELYN_2 1506
#undef  TRAINER_COOLTRAINER_LEROY_2
#define TRAINER_COOLTRAINER_LEROY_2 1507
#undef  TRAINER_COOLTRAINER_MICHELLE_2
#define TRAINER_COOLTRAINER_MICHELLE_2 1508
#undef  TRAINER_COOL_COUPLE_LEX_NYA_2
#define TRAINER_COOL_COUPLE_LEX_NYA_2 1509
#undef  TRAINER_BUG_CATCHER_COLTON_2
#define TRAINER_BUG_CATCHER_COLTON_2 1510
#undef  TRAINER_BUG_CATCHER_COLTON_3
#define TRAINER_BUG_CATCHER_COLTON_3 1511
#undef  TRAINER_BUG_CATCHER_COLTON_4
#define TRAINER_BUG_CATCHER_COLTON_4 1512
#undef  TRAINER_SWIMMER_MALE_MATTHEW_2
#define TRAINER_SWIMMER_MALE_MATTHEW_2 1513
#undef  TRAINER_SWIMMER_MALE_TONY_2
#define TRAINER_SWIMMER_MALE_TONY_2 1514
#undef  TRAINER_SWIMMER_FEMALE_MELISSA_2
#define TRAINER_SWIMMER_FEMALE_MELISSA_2 1515
#undef  TRAINER_ELITE_FOUR_LORELEI_2
#define TRAINER_ELITE_FOUR_LORELEI_2 1516
#undef  TRAINER_ELITE_FOUR_BRUNO_2
#define TRAINER_ELITE_FOUR_BRUNO_2 1517
#undef  TRAINER_ELITE_FOUR_AGATHA_2
#define TRAINER_ELITE_FOUR_AGATHA_2 1518
#undef  TRAINER_ELITE_FOUR_LANCE_2
#define TRAINER_ELITE_FOUR_LANCE_2 1519
#undef  TRAINER_CHAMPION_REMATCH_SQUIRTLE
#define TRAINER_CHAMPION_REMATCH_SQUIRTLE 1520
#undef  TRAINER_CHAMPION_REMATCH_BULBASAUR
#define TRAINER_CHAMPION_REMATCH_BULBASAUR 1521
#undef  TRAINER_CHAMPION_REMATCH_CHARMANDER
#define TRAINER_CHAMPION_REMATCH_CHARMANDER 1522
#undef  TRAINER_CUE_BALL_PAXTON
#define TRAINER_CUE_BALL_PAXTON 1523

// Kanto rival entries (standalone battles, not from trainers_frlg.h data)
// 855-870 are gym leader T6/T7 entries; use the gap at 871-873 to avoid collision.
#undef TRAINER_RIVAL_OAKS_LAB_SQUIRTLE
#define TRAINER_RIVAL_OAKS_LAB_SQUIRTLE   871
#undef TRAINER_RIVAL_OAKS_LAB_BULBASAUR
#define TRAINER_RIVAL_OAKS_LAB_BULBASAUR  872
#undef TRAINER_RIVAL_OAKS_LAB_CHARMANDER
#define TRAINER_RIVAL_OAKS_LAB_CHARMANDER 873
#endif

#define TRAINER_NONE                          0
#define TRAINER_SAWYER_1                      1
#define TRAINER_GRUNT_AQUA_HIDEOUT_1          2
#define TRAINER_GRUNT_AQUA_HIDEOUT_2          3
#define TRAINER_GRUNT_AQUA_HIDEOUT_3          4
#define TRAINER_GRUNT_AQUA_HIDEOUT_4          5
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1       6
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2       7
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3       8
#define TRAINER_GABRIELLE_1                   9
#define TRAINER_GRUNT_PETALBURG_WOODS        10
#define TRAINER_MARCEL                       11
#define TRAINER_ALBERTO                      12
#define TRAINER_ED                           13
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4      14
#define TRAINER_DECLAN                       15
#define TRAINER_GRUNT_RUSTURF_TUNNEL         16
#define TRAINER_GRUNT_WEATHER_INST_1         17
#define TRAINER_GRUNT_WEATHER_INST_2         18
#define TRAINER_GRUNT_WEATHER_INST_3         19
#define TRAINER_GRUNT_MUSEUM_1               20
#define TRAINER_GRUNT_MUSEUM_2               21
#define TRAINER_GRUNT_SPACE_CENTER_1         22
#define TRAINER_GRUNT_MT_PYRE_1              23
#define TRAINER_GRUNT_MT_PYRE_2              24
#define TRAINER_GRUNT_MT_PYRE_3              25
#define TRAINER_GRUNT_WEATHER_INST_4         26
#define TRAINER_GRUNT_AQUA_HIDEOUT_5         27
#define TRAINER_GRUNT_AQUA_HIDEOUT_6         28
#define TRAINER_FREDRICK                     29
#define TRAINER_MATT                         30
#define TRAINER_ZANDER                       31
#define TRAINER_SHELLY_WEATHER_INSTITUTE     32
#define TRAINER_SHELLY_SEAFLOOR_CAVERN       33
#define TRAINER_ARCHIE                       34
#define TRAINER_LEAH                         35
#define TRAINER_DAISY                        36
#define TRAINER_ROSE_1                       37
#define TRAINER_FELIX                        38
#define TRAINER_VIOLET                       39
#define TRAINER_ROSE_2                       40
#define TRAINER_ROSE_3                       41
#define TRAINER_ROSE_4                       42
#define TRAINER_ROSE_5                       43
#define TRAINER_DUSTY_1                      44
#define TRAINER_CHIP                         45
#define TRAINER_FOSTER                       46
#define TRAINER_DUSTY_2                      47
#define TRAINER_DUSTY_3                      48
#define TRAINER_DUSTY_4                      49
#define TRAINER_DUSTY_5                      50
#define TRAINER_GABBY_AND_TY_1               51
#define TRAINER_GABBY_AND_TY_2               52
#define TRAINER_GABBY_AND_TY_3               53
#define TRAINER_GABBY_AND_TY_4               54
#define TRAINER_GABBY_AND_TY_5               55
#define TRAINER_GABBY_AND_TY_6               56
#define TRAINER_LOLA_1                       57
#define TRAINER_AUSTINA                      58
#define TRAINER_GWEN                         59
#define TRAINER_LOLA_2                       60
#define TRAINER_LOLA_3                       61
#define TRAINER_LOLA_4                       62
#define TRAINER_LOLA_5                       63
#define TRAINER_RICKY_1                      64
#define TRAINER_SIMON                        65
#define TRAINER_CHARLIE                      66
#define TRAINER_RICKY_2                      67
#define TRAINER_RICKY_3                      68
#define TRAINER_RICKY_4                      69
#define TRAINER_RICKY_5                      70
#define TRAINER_RANDALL                      71
#define TRAINER_PARKER                       72
#define TRAINER_GEORGE                       73
#define TRAINER_BERKE                        74
#define TRAINER_BRAXTON                      75
#define TRAINER_VINCENT                      76
#define TRAINER_LEROY                        77
#define TRAINER_WILTON_1                     78
#define TRAINER_EDGAR                        79
#define TRAINER_ALBERT                       80
#define TRAINER_SAMUEL                       81
#define TRAINER_VITO                         82
#define TRAINER_OWEN                         83
#define TRAINER_WILTON_2                     84
#define TRAINER_WILTON_3                     85
#define TRAINER_WILTON_4                     86
#define TRAINER_WILTON_5                     87
#define TRAINER_WARREN                       88
#define TRAINER_MARY                         89
#define TRAINER_ALEXIA                       90
#define TRAINER_JODY                         91
#define TRAINER_WENDY                        92
#define TRAINER_KEIRA                        93
#define TRAINER_BROOKE_1                     94
#define TRAINER_JENNIFER                     95
#define TRAINER_HOPE                         96
#define TRAINER_SHANNON                      97
#define TRAINER_MICHELLE                     98
#define TRAINER_CAROLINE                     99
#define TRAINER_JULIE                       100
#define TRAINER_BROOKE_2                    101
#define TRAINER_BROOKE_3                    102
#define TRAINER_BROOKE_4                    103
#define TRAINER_BROOKE_5                    104
#define TRAINER_PATRICIA                    105
#define TRAINER_KINDRA                      106
#define TRAINER_TAMMY                       107
#define TRAINER_VALERIE_1                   108
#define TRAINER_TASHA                       109
#define TRAINER_VALERIE_2                   110
#define TRAINER_VALERIE_3                   111
#define TRAINER_VALERIE_4                   112
#define TRAINER_VALERIE_5                   113
#define TRAINER_CINDY_1                     114
#define TRAINER_DAPHNE                      115
#define TRAINER_GRUNT_SPACE_CENTER_2        116
#define TRAINER_CINDY_2                     117
#define TRAINER_BRIANNA                     118
#define TRAINER_NAOMI                       119
#define TRAINER_CINDY_3                     120
#define TRAINER_CINDY_4                     121
#define TRAINER_CINDY_5                     122
#define TRAINER_CINDY_6                     123
#define TRAINER_MELISSA                     124
#define TRAINER_SHEILA                      125
#define TRAINER_SHIRLEY                     126
#define TRAINER_JESSICA_1                   127
#define TRAINER_CONNIE                      128
#define TRAINER_BRIDGET                     129
#define TRAINER_OLIVIA                      130
#define TRAINER_TIFFANY                     131
#define TRAINER_JESSICA_2                   132
#define TRAINER_JESSICA_3                   133
#define TRAINER_JESSICA_4                   134
#define TRAINER_JESSICA_5                   135
#define TRAINER_WINSTON_1                   136
#define TRAINER_MOLLIE                      137
#define TRAINER_GARRET                      138
#define TRAINER_WINSTON_2                   139
#define TRAINER_WINSTON_3                   140
#define TRAINER_WINSTON_4                   141
#define TRAINER_WINSTON_5                   142
#define TRAINER_STEVE_1                     143
#define TRAINER_THALIA_1                    144
#define TRAINER_MARK                        145
#define TRAINER_GRUNT_MT_CHIMNEY_1          146
#define TRAINER_STEVE_2                     147
#define TRAINER_STEVE_3                     148
#define TRAINER_STEVE_4                     149
#define TRAINER_STEVE_5                     150
#define TRAINER_LUIS                        151
#define TRAINER_DOMINIK                     152
#define TRAINER_DOUGLAS                     153
#define TRAINER_DARRIN                      154
#define TRAINER_TONY_1                      155
#define TRAINER_JEROME                      156
#define TRAINER_MATTHEW                     157
#define TRAINER_DAVID                       158
#define TRAINER_SPENCER                     159
#define TRAINER_ROLAND                      160
#define TRAINER_NOLEN                       161
#define TRAINER_STAN                        162
#define TRAINER_BARRY                       163
#define TRAINER_DEAN                        164
#define TRAINER_RODNEY                      165
#define TRAINER_RICHARD                     166
#define TRAINER_HERMAN                      167
#define TRAINER_SANTIAGO                    168
#define TRAINER_GILBERT                     169
#define TRAINER_FRANKLIN                    170
#define TRAINER_KEVIN                       171
#define TRAINER_JACK                        172
#define TRAINER_DUDLEY                      173
#define TRAINER_CHAD                        174
#define TRAINER_TONY_2                      175
#define TRAINER_TONY_3                      176
#define TRAINER_TONY_4                      177
#define TRAINER_TONY_5                      178
#define TRAINER_TAKAO                       179
#define TRAINER_HITOSHI                     180
#define TRAINER_KIYO                        181
#define TRAINER_KOICHI                      182
#define TRAINER_NOB_1                       183
#define TRAINER_NOB_2                       184
#define TRAINER_NOB_3                       185
#define TRAINER_NOB_4                       186
#define TRAINER_NOB_5                       187
#define TRAINER_YUJI                        188
#define TRAINER_DAISUKE                     189
#define TRAINER_ATSUSHI                     190
#define TRAINER_KIRK                        191
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        192
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        193
#define TRAINER_SHAWN                       194
#define TRAINER_FERNANDO_1                  195
#define TRAINER_DALTON_1                    196
#define TRAINER_DALTON_2                    197
#define TRAINER_DALTON_3                    198
#define TRAINER_DALTON_4                    199
#define TRAINER_DALTON_5                    200
#define TRAINER_COLE                        201
#define TRAINER_JEFF                        202
#define TRAINER_AXLE                        203
#define TRAINER_JACE                        204
#define TRAINER_KEEGAN                      205
#define TRAINER_BERNIE_1                    206
#define TRAINER_BERNIE_2                    207
#define TRAINER_BERNIE_3                    208
#define TRAINER_BERNIE_4                    209
#define TRAINER_BERNIE_5                    210
#define TRAINER_DREW                        211
#define TRAINER_BEAU                        212
#define TRAINER_LARRY                       213
#define TRAINER_SHANE                       214
#define TRAINER_JUSTIN                      215
#define TRAINER_ETHAN_1                     216
#define TRAINER_AUTUMN                      217
#define TRAINER_TRAVIS                      218
#define TRAINER_ETHAN_2                     219
#define TRAINER_ETHAN_3                     220
#define TRAINER_ETHAN_4                     221
#define TRAINER_ETHAN_5                     222
#define TRAINER_BRENT                       223
#define TRAINER_DONALD                      224
#define TRAINER_TAYLOR                      225
#define TRAINER_JEFFREY_1                   226
#define TRAINER_DEREK                       227
#define TRAINER_JEFFREY_2                   228
#define TRAINER_JEFFREY_3                   229
#define TRAINER_JEFFREY_4                   230
#define TRAINER_JEFFREY_5                   231
#define TRAINER_EDWARD                      232
#define TRAINER_PRESTON                     233
#define TRAINER_VIRGIL                      234
#define TRAINER_BLAKE                       235
#define TRAINER_WILLIAM                     236
#define TRAINER_JOSHUA                      237
#define TRAINER_CAMERON_1                   238
#define TRAINER_CAMERON_2                   239
#define TRAINER_CAMERON_3                   240
#define TRAINER_CAMERON_4                   241
#define TRAINER_CAMERON_5                   242
#define TRAINER_JACLYN                      243
#define TRAINER_HANNAH                      244
#define TRAINER_SAMANTHA                    245
#define TRAINER_MAURA                       246
#define TRAINER_KAYLA                       247
#define TRAINER_ALEXIS                      248
#define TRAINER_JACKI_1                     249
#define TRAINER_JACKI_2                     250
#define TRAINER_JACKI_3                     251
#define TRAINER_JACKI_4                     252
#define TRAINER_JACKI_5                     253
#define TRAINER_WALTER_1                    254
#define TRAINER_MICAH                       255
#define TRAINER_THOMAS                      256
#define TRAINER_WALTER_2                    257
#define TRAINER_WALTER_3                    258
#define TRAINER_WALTER_4                    259
#define TRAINER_WALTER_5                    260
#define TRAINER_SIDNEY                      261
#define TRAINER_PHOEBE                      262
#define TRAINER_GLACIA                      263
#define TRAINER_DRAKE                       264
#define TRAINER_ROXANNE_1                   265
#define TRAINER_BRAWLY_1                    266
#define TRAINER_WATTSON_1                   267
#define TRAINER_FLANNERY_1                  268
#define TRAINER_NORMAN_1                    269
#define TRAINER_WINONA_1                    270
#define TRAINER_TATE_AND_LIZA_1             271
#define TRAINER_JUAN_1                      272
#define TRAINER_JERRY_1                     273
#define TRAINER_TED                         274
#define TRAINER_PAUL                        275
#define TRAINER_JERRY_2                     276
#define TRAINER_JERRY_3                     277
#define TRAINER_JERRY_4                     278
#define TRAINER_JERRY_5                     279
#define TRAINER_KAREN_1                     280
#define TRAINER_GEORGIA                     281
#define TRAINER_KAREN_2                     282
#define TRAINER_KAREN_3                     283
#define TRAINER_KAREN_4                     284
#define TRAINER_KAREN_5                     285
#define TRAINER_KATE_AND_JOY                286
#define TRAINER_ANNA_AND_MEG_1              287
#define TRAINER_ANNA_AND_MEG_2              288
#define TRAINER_ANNA_AND_MEG_3              289
#define TRAINER_ANNA_AND_MEG_4              290
#define TRAINER_ANNA_AND_MEG_5              291
#define TRAINER_VICTOR                      292
#define TRAINER_MIGUEL_1                    293
#define TRAINER_COLTON                      294
#define TRAINER_MIGUEL_2                    295
#define TRAINER_MIGUEL_3                    296
#define TRAINER_MIGUEL_4                    297
#define TRAINER_MIGUEL_5                    298
#define TRAINER_VICTORIA                    299
#define TRAINER_VANESSA                     300
#define TRAINER_BETHANY                     301
#define TRAINER_ISABEL_1                    302
#define TRAINER_ISABEL_2                    303
#define TRAINER_ISABEL_3                    304
#define TRAINER_ISABEL_4                    305
#define TRAINER_ISABEL_5                    306
#define TRAINER_TIMOTHY_1                   307
#define TRAINER_TIMOTHY_2                   308
#define TRAINER_TIMOTHY_3                   309
#define TRAINER_TIMOTHY_4                   310
#define TRAINER_TIMOTHY_5                   311
#define TRAINER_VICKY                       312
#define TRAINER_SHELBY_1                    313
#define TRAINER_SHELBY_2                    314
#define TRAINER_SHELBY_3                    315
#define TRAINER_SHELBY_4                    316
#define TRAINER_SHELBY_5                    317
#define TRAINER_CALVIN_1                    318
#define TRAINER_BILLY                       319
#define TRAINER_JOSH                        320
#define TRAINER_TOMMY                       321
#define TRAINER_JOEY                        322
#define TRAINER_BEN                         323
#define TRAINER_QUINCY                      324
#define TRAINER_KATELYNN                    325
#define TRAINER_JAYLEN                      326
#define TRAINER_DILLON                      327
#define TRAINER_CALVIN_2                    328
#define TRAINER_CALVIN_3                    329
#define TRAINER_CALVIN_4                    330
#define TRAINER_CALVIN_5                    331
#define TRAINER_EDDIE                       332
#define TRAINER_ALLEN                       333
#define TRAINER_TIMMY                       334
#define TRAINER_WALLACE                     335
#define TRAINER_ANDREW                      336
#define TRAINER_IVAN                        337
#define TRAINER_CLAUDE                      338
#define TRAINER_ELLIOT_1                    339
#define TRAINER_NED                         340
#define TRAINER_DALE                        341
#define TRAINER_NOLAN                       342
#define TRAINER_BARNY                       343
#define TRAINER_WADE                        344
#define TRAINER_CARTER                      345
#define TRAINER_ELLIOT_2                    346
#define TRAINER_ELLIOT_3                    347
#define TRAINER_ELLIOT_4                    348
#define TRAINER_ELLIOT_5                    349
#define TRAINER_RONALD                      350
#define TRAINER_JACOB                       351
#define TRAINER_ANTHONY                     352
#define TRAINER_BENJAMIN_1                  353
#define TRAINER_BENJAMIN_2                  354
#define TRAINER_BENJAMIN_3                  355
#define TRAINER_BENJAMIN_4                  356
#define TRAINER_BENJAMIN_5                  357
#define TRAINER_ABIGAIL_1                   358
#define TRAINER_JASMINE                     359
#define TRAINER_ABIGAIL_2                   360
#define TRAINER_ABIGAIL_3                   361
#define TRAINER_ABIGAIL_4                   362
#define TRAINER_ABIGAIL_5                   363
#define TRAINER_DYLAN_1                     364
#define TRAINER_DYLAN_2                     365
#define TRAINER_DYLAN_3                     366
#define TRAINER_DYLAN_4                     367
#define TRAINER_DYLAN_5                     368
#define TRAINER_MARIA_1                     369
#define TRAINER_MARIA_2                     370
#define TRAINER_MARIA_3                     371
#define TRAINER_MARIA_4                     372
#define TRAINER_MARIA_5                     373
#define TRAINER_CAMDEN                      374
#define TRAINER_DEMETRIUS                   375
#define TRAINER_ISAIAH_1                    376
#define TRAINER_PABLO_1                     377
#define TRAINER_CHASE                       378
#define TRAINER_ISAIAH_2                    379
#define TRAINER_ISAIAH_3                    380
#define TRAINER_ISAIAH_4                    381
#define TRAINER_ISAIAH_5                    382
#define TRAINER_ISOBEL                      383
#define TRAINER_DONNY                       384
#define TRAINER_TALIA                       385
#define TRAINER_KATELYN_1                   386
#define TRAINER_ALLISON                     387
#define TRAINER_KATELYN_2                   388
#define TRAINER_KATELYN_3                   389
#define TRAINER_KATELYN_4                   390
#define TRAINER_KATELYN_5                   391
#define TRAINER_NICOLAS_1                   392
#define TRAINER_NICOLAS_2                   393
#define TRAINER_NICOLAS_3                   394
#define TRAINER_NICOLAS_4                   395
#define TRAINER_NICOLAS_5                   396
#define TRAINER_AARON                       397
#define TRAINER_PERRY                       398
#define TRAINER_HUGH                        399
#define TRAINER_PHIL                        400
#define TRAINER_JARED                       401
#define TRAINER_HUMBERTO                    402
#define TRAINER_PRESLEY                     403
#define TRAINER_EDWARDO                     404
#define TRAINER_COLIN                       405
#define TRAINER_ROBERT_1                    406
#define TRAINER_BENNY                       407
#define TRAINER_CHESTER                     408
#define TRAINER_ROBERT_2                    409
#define TRAINER_ROBERT_3                    410
#define TRAINER_ROBERT_4                    411
#define TRAINER_ROBERT_5                    412
#define TRAINER_ALEX                        413
#define TRAINER_BECK                        414
#define TRAINER_YASU                        415
#define TRAINER_TAKASHI                     416
#define TRAINER_DIANNE                      417
#define TRAINER_JANI                        418
#define TRAINER_LAO_1                       419
#define TRAINER_LUNG                        420
#define TRAINER_LAO_2                       421
#define TRAINER_LAO_3                       422
#define TRAINER_LAO_4                       423
#define TRAINER_LAO_5                       424
#define TRAINER_JOCELYN                     425
#define TRAINER_LAURA                       426
#define TRAINER_CYNDY_1                     427
#define TRAINER_CORA                        428
#define TRAINER_PAULA                       429
#define TRAINER_CYNDY_2                     430
#define TRAINER_CYNDY_3                     431
#define TRAINER_CYNDY_4                     432
#define TRAINER_CYNDY_5                     433
#define TRAINER_MADELINE_1                  434
#define TRAINER_CLARISSA                    435
#define TRAINER_ANGELICA                    436
#define TRAINER_MADELINE_2                  437
#define TRAINER_MADELINE_3                  438
#define TRAINER_MADELINE_4                  439
#define TRAINER_MADELINE_5                  440
#define TRAINER_BEVERLY                     441
#define TRAINER_IMANI                       442
#define TRAINER_KYLA                        443
#define TRAINER_DENISE                      444
#define TRAINER_BETH                        445
#define TRAINER_TARA                        446
#define TRAINER_MISSY                       447
#define TRAINER_ALICE                       448
#define TRAINER_JENNY_1                     449
#define TRAINER_GRACE                       450
#define TRAINER_TANYA                       451
#define TRAINER_SHARON                      452
#define TRAINER_NIKKI                       453
#define TRAINER_BRENDA                      454
#define TRAINER_KATIE                       455
#define TRAINER_SUSIE                       456
#define TRAINER_KARA                        457
#define TRAINER_DANA                        458
#define TRAINER_SIENNA                      459
#define TRAINER_DEBRA                       460
#define TRAINER_LINDA                       461
#define TRAINER_KAYLEE                      462
#define TRAINER_LAUREL                      463
#define TRAINER_CARLEE                      464
#define TRAINER_JENNY_2                     465
#define TRAINER_JENNY_3                     466
#define TRAINER_JENNY_4                     467
#define TRAINER_JENNY_5                     468
#define TRAINER_HEIDI                       469
#define TRAINER_BECKY                       470
#define TRAINER_CAROL                       471
#define TRAINER_NANCY                       472
#define TRAINER_MARTHA                      473
#define TRAINER_DIANA_1                     474
#define TRAINER_CEDRIC                      475
#define TRAINER_IRENE                       476
#define TRAINER_DIANA_2                     477
#define TRAINER_DIANA_3                     478
#define TRAINER_DIANA_4                     479
#define TRAINER_DIANA_5                     480
#define TRAINER_AMY_AND_LIV_1               481
#define TRAINER_AMY_AND_LIV_2               482
#define TRAINER_GINA_AND_MIA_1              483
#define TRAINER_MIU_AND_YUKI                484
#define TRAINER_AMY_AND_LIV_3               485
#define TRAINER_GINA_AND_MIA_2              486
#define TRAINER_AMY_AND_LIV_4               487
#define TRAINER_AMY_AND_LIV_5               488
#define TRAINER_AMY_AND_LIV_6               489
#define TRAINER_HUEY                        490
#define TRAINER_EDMOND                      491
#define TRAINER_ERNEST_1                    492
#define TRAINER_DWAYNE                      493
#define TRAINER_PHILLIP                     494
#define TRAINER_LEONARD                     495
#define TRAINER_DUNCAN                      496
#define TRAINER_ERNEST_2                    497
#define TRAINER_ERNEST_3                    498
#define TRAINER_ERNEST_4                    499
#define TRAINER_ERNEST_5                    500
#define TRAINER_ELI                         501
#define TRAINER_ANNIKA                      502
#define TRAINER_JAZMYN                      503
#define TRAINER_JONAS                       504
#define TRAINER_KAYLEY                      505
#define TRAINER_AURON                       506
#define TRAINER_KELVIN                      507
#define TRAINER_MARLEY                      508
#define TRAINER_REYNA                       509
#define TRAINER_HUDSON                      510
#define TRAINER_CONOR                       511
#define TRAINER_EDWIN_1                     512
#define TRAINER_HECTOR                      513
#define TRAINER_TABITHA_MOSSDEEP            514
#define TRAINER_EDWIN_2                     515
#define TRAINER_EDWIN_3                     516
#define TRAINER_EDWIN_4                     517
#define TRAINER_EDWIN_5                     518
#define TRAINER_WALLY_VR_1                  519
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    520
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    521
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    522
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   523
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   524
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   525
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   526
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   527
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   528
#define TRAINER_MAY_ROUTE_103_MUDKIP        529
#define TRAINER_MAY_ROUTE_110_MUDKIP        530
#define TRAINER_MAY_ROUTE_119_MUDKIP        531
#define TRAINER_MAY_ROUTE_103_TREECKO       532
#define TRAINER_MAY_ROUTE_110_TREECKO       533
#define TRAINER_MAY_ROUTE_119_TREECKO       534
#define TRAINER_MAY_ROUTE_103_TORCHIC       535
#define TRAINER_MAY_ROUTE_110_TORCHIC       536
#define TRAINER_MAY_ROUTE_119_TORCHIC       537
#define TRAINER_ISAAC_1                     538
#define TRAINER_DAVIS                       539
#define TRAINER_MITCHELL                    540
#define TRAINER_ISAAC_2                     541
#define TRAINER_ISAAC_3                     542
#define TRAINER_ISAAC_4                     543
#define TRAINER_ISAAC_5                     544
#define TRAINER_LYDIA_1                     545
#define TRAINER_HALLE                       546
#define TRAINER_GARRISON                    547
#define TRAINER_LYDIA_2                     548
#define TRAINER_LYDIA_3                     549
#define TRAINER_LYDIA_4                     550
#define TRAINER_LYDIA_5                     551
#define TRAINER_JACKSON_1                   552
#define TRAINER_LORENZO                     553
#define TRAINER_SEBASTIAN                   554
#define TRAINER_JACKSON_2                   555
#define TRAINER_JACKSON_3                   556
#define TRAINER_JACKSON_4                   557
#define TRAINER_JACKSON_5                   558
#define TRAINER_CATHERINE_1                 559
#define TRAINER_JENNA                       560
#define TRAINER_SOPHIA                      561
#define TRAINER_CATHERINE_2                 562
#define TRAINER_CATHERINE_3                 563
#define TRAINER_CATHERINE_4                 564
#define TRAINER_CATHERINE_5                 565
#define TRAINER_JULIO                       566
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     567
#define TRAINER_GRUNT_UNUSED                568
#define TRAINER_GRUNT_MT_PYRE_4             569
#define TRAINER_GRUNT_JAGGED_PASS           570
#define TRAINER_MARC                        571
#define TRAINER_BRENDEN                     572
#define TRAINER_LILITH                      573
#define TRAINER_CRISTIAN                    574
#define TRAINER_SYLVIA                      575
#define TRAINER_LEONARDO                    576
#define TRAINER_ATHENA                      577
#define TRAINER_HARRISON                    578
#define TRAINER_GRUNT_MT_CHIMNEY_2          579
#define TRAINER_CLARENCE                    580
#define TRAINER_TERRY                       581
#define TRAINER_NATE                        582
#define TRAINER_KATHLEEN                    583
#define TRAINER_CLIFFORD                    584
#define TRAINER_NICHOLAS                    585
#define TRAINER_GRUNT_SPACE_CENTER_3        586
#define TRAINER_GRUNT_SPACE_CENTER_4        587
#define TRAINER_GRUNT_SPACE_CENTER_5        588
#define TRAINER_GRUNT_SPACE_CENTER_6        589
#define TRAINER_GRUNT_SPACE_CENTER_7        590
#define TRAINER_MACEY                       591
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    592
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     593
#define TRAINER_PAXTON                      594
#define TRAINER_ISABELLA                    595
#define TRAINER_GRUNT_WEATHER_INST_5        596
#define TRAINER_TABITHA_MT_CHIMNEY          597
#define TRAINER_JONATHAN                    598
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    599
#define TRAINER_MAY_RUSTBORO_MUDKIP         600
#define TRAINER_MAXIE_MAGMA_HIDEOUT         601
#define TRAINER_MAXIE_MT_CHIMNEY            602
#define TRAINER_TIANA                       603
#define TRAINER_HALEY_1                     604
#define TRAINER_JANICE                      605
#define TRAINER_VIVI                        606
#define TRAINER_HALEY_2                     607
#define TRAINER_HALEY_3                     608
#define TRAINER_HALEY_4                     609
#define TRAINER_HALEY_5                     610
#define TRAINER_SALLY                       611
#define TRAINER_ROBIN                       612
#define TRAINER_ANDREA                      613
#define TRAINER_CRISSY                      614
#define TRAINER_RICK                        615
#define TRAINER_LYLE                        616
#define TRAINER_JOSE                        617
#define TRAINER_DOUG                        618
#define TRAINER_GREG                        619
#define TRAINER_KENT                        620
#define TRAINER_JAMES_1                     621
#define TRAINER_JAMES_2                     622
#define TRAINER_JAMES_3                     623
#define TRAINER_JAMES_4                     624
#define TRAINER_JAMES_5                     625
#define TRAINER_BRICE                       626
#define TRAINER_TRENT_1                     627
#define TRAINER_LENNY                       628
#define TRAINER_LUCAS_1                     629
#define TRAINER_ALAN                        630
#define TRAINER_CLARK                       631
#define TRAINER_ERIC                        632
#define TRAINER_LUCAS_2                     633
#define TRAINER_MIKE_1                      634
#define TRAINER_MIKE_2                      635
#define TRAINER_TRENT_2                     636
#define TRAINER_TRENT_3                     637
#define TRAINER_TRENT_4                     638
#define TRAINER_TRENT_5                     639
#define TRAINER_DEZ_AND_LUKE                640
#define TRAINER_LEA_AND_JED                 641
#define TRAINER_KIRA_AND_DAN_1              642
#define TRAINER_KIRA_AND_DAN_2              643
#define TRAINER_KIRA_AND_DAN_3              644
#define TRAINER_KIRA_AND_DAN_4              645
#define TRAINER_KIRA_AND_DAN_5              646
#define TRAINER_JOHANNA                     647
#define TRAINER_GERALD                      648
#define TRAINER_VIVIAN                      649
#define TRAINER_DANIELLE                    650
#define TRAINER_HIDEO                       651
#define TRAINER_KEIGO                       652
#define TRAINER_RILEY                       653
#define TRAINER_FLINT                       654
#define TRAINER_ASHLEY                      655
#define TRAINER_WALLY_MAUVILLE              656
#define TRAINER_WALLY_VR_2                  657
#define TRAINER_WALLY_VR_3                  658
#define TRAINER_WALLY_VR_4                  659
#define TRAINER_WALLY_VR_5                  660
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     661
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    662
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    663
#define TRAINER_MAY_LILYCOVE_MUDKIP         664
#define TRAINER_MAY_LILYCOVE_TREECKO        665
#define TRAINER_MAY_LILYCOVE_TORCHIC        666
#define TRAINER_JONAH                       667
#define TRAINER_HENRY                       668
#define TRAINER_ROGER                       669
#define TRAINER_ALEXA                       670
#define TRAINER_RUBEN                       671
#define TRAINER_KOJI_1                      672
#define TRAINER_WAYNE                       673
#define TRAINER_AIDAN                       674
#define TRAINER_REED                        675
#define TRAINER_TISHA                       676
#define TRAINER_TORI_AND_TIA                677
#define TRAINER_KIM_AND_IRIS                678
#define TRAINER_TYRA_AND_IVY                679
#define TRAINER_MEL_AND_PAUL                680
#define TRAINER_JOHN_AND_JAY_1              681
#define TRAINER_JOHN_AND_JAY_2              682
#define TRAINER_JOHN_AND_JAY_3              683
#define TRAINER_JOHN_AND_JAY_4              684
#define TRAINER_JOHN_AND_JAY_5              685
#define TRAINER_RELI_AND_IAN                686
#define TRAINER_LILA_AND_ROY_1              687
#define TRAINER_LILA_AND_ROY_2              688
#define TRAINER_LILA_AND_ROY_3              689
#define TRAINER_LILA_AND_ROY_4              690
#define TRAINER_LILA_AND_ROY_5              691
#define TRAINER_LISA_AND_RAY                692
#define TRAINER_CHRIS                       693
#define TRAINER_DAWSON                      694
#define TRAINER_SARAH                       695
#define TRAINER_DARIAN                      696
#define TRAINER_HAILEY                      697
#define TRAINER_CHANDLER                    698
#define TRAINER_KALEB                       699
#define TRAINER_JOSEPH                      700
#define TRAINER_ALYSSA                      701
#define TRAINER_MARCOS                      702
#define TRAINER_RHETT                       703
#define TRAINER_TYRON                       704
#define TRAINER_CELINA                      705
#define TRAINER_BIANCA                      706
#define TRAINER_HAYDEN                      707
#define TRAINER_SOPHIE                      708
#define TRAINER_COBY                        709
#define TRAINER_LAWRENCE                    710
#define TRAINER_WYATT                       711
#define TRAINER_ANGELINA                    712
#define TRAINER_KAI                         713
#define TRAINER_CHARLOTTE                   714
#define TRAINER_DEANDRE                     715
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       716
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       717
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       718
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       719
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       720
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       721
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       722
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       723
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       724
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      725
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      726
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      727
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      728
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      729
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      730
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      731
#define TRAINER_TABITHA_MAGMA_HIDEOUT       732
#define TRAINER_DARCY                       733
#define TRAINER_MAXIE_MOSSDEEP              734
#define TRAINER_PETE                        735
#define TRAINER_ISABELLE                    736
#define TRAINER_ANDRES_1                    737
#define TRAINER_JOSUE                       738
#define TRAINER_CAMRON                      739
#define TRAINER_CORY_1                      740
#define TRAINER_CAROLINA                    741
#define TRAINER_ELIJAH                      742
#define TRAINER_CELIA                       743
#define TRAINER_BRYAN                       744
#define TRAINER_BRANDEN                     745
#define TRAINER_BRYANT                      746
#define TRAINER_SHAYLA                      747
#define TRAINER_KYRA                        748
#define TRAINER_JAIDEN                      749
#define TRAINER_ALIX                        750
#define TRAINER_HELENE                      751
#define TRAINER_MARLENE                     752
#define TRAINER_DEVAN                       753
#define TRAINER_JOHNSON                     754
#define TRAINER_MELINA                      755
#define TRAINER_BRANDI                      756
#define TRAINER_AISHA                       757
#define TRAINER_MAKAYLA                     758
#define TRAINER_FABIAN                      759
#define TRAINER_DAYTON                      760
#define TRAINER_RACHEL                      761
#define TRAINER_LEONEL                      762
#define TRAINER_CALLIE                      763
#define TRAINER_CALE                        764
#define TRAINER_MYLES                       765
#define TRAINER_PAT                         766
#define TRAINER_CRISTIN_1                   767
#define TRAINER_MAY_RUSTBORO_TREECKO        768
#define TRAINER_MAY_RUSTBORO_TORCHIC        769
#define TRAINER_ROXANNE_2                   770
#define TRAINER_ROXANNE_3                   771
#define TRAINER_ROXANNE_4                   772
#define TRAINER_ROXANNE_5                   773
#define TRAINER_BRAWLY_2                    774
#define TRAINER_BRAWLY_3                    775
#define TRAINER_BRAWLY_4                    776
#define TRAINER_BRAWLY_5                    777
#define TRAINER_WATTSON_2                   778
#define TRAINER_WATTSON_3                   779
#define TRAINER_WATTSON_4                   780
#define TRAINER_WATTSON_5                   781
#define TRAINER_FLANNERY_2                  782
#define TRAINER_FLANNERY_3                  783
#define TRAINER_FLANNERY_4                  784
#define TRAINER_FLANNERY_5                  785
#define TRAINER_NORMAN_2                    786
#define TRAINER_NORMAN_3                    787
#define TRAINER_NORMAN_4                    788
#define TRAINER_NORMAN_5                    789
#define TRAINER_WINONA_2                    790
#define TRAINER_WINONA_3                    791
#define TRAINER_WINONA_4                    792
#define TRAINER_WINONA_5                    793
#define TRAINER_TATE_AND_LIZA_2             794
#define TRAINER_TATE_AND_LIZA_3             795
#define TRAINER_TATE_AND_LIZA_4             796
#define TRAINER_TATE_AND_LIZA_5             797
#define TRAINER_JUAN_2                      798
#define TRAINER_JUAN_3                      799
#define TRAINER_JUAN_4                      800
#define TRAINER_JUAN_5                      801
#define TRAINER_ROXANNE_6                   855
#define TRAINER_ROXANNE_7                   856
#define TRAINER_BRAWLY_6                    857
#define TRAINER_BRAWLY_7                    858
#define TRAINER_WATTSON_6                   859
#define TRAINER_WATTSON_7                   860
#define TRAINER_FLANNERY_6                  861
#define TRAINER_FLANNERY_7                  862
#define TRAINER_NORMAN_6                    863
#define TRAINER_NORMAN_7                    864
#define TRAINER_WINONA_6                    865
#define TRAINER_WINONA_7                    866
#define TRAINER_TATE_AND_LIZA_6             867
#define TRAINER_TATE_AND_LIZA_7             868
#define TRAINER_JUAN_6                      869
#define TRAINER_JUAN_7                      870
#define TRAINER_ANGELO                      802
#define TRAINER_DARIUS                      803
#define TRAINER_STEVEN                      804
#define TRAINER_ANABEL                      805
#define TRAINER_TUCKER                      806
#define TRAINER_SPENSER                     807
#define TRAINER_GRETA                       808
#define TRAINER_NOLAND                      809
#define TRAINER_LUCY                        810
#define TRAINER_BRANDON                     811
#define TRAINER_ANDRES_2                    812
#define TRAINER_ANDRES_3                    813
#define TRAINER_ANDRES_4                    814
#define TRAINER_ANDRES_5                    815
#define TRAINER_CORY_2                      816
#define TRAINER_CORY_3                      817
#define TRAINER_CORY_4                      818
#define TRAINER_CORY_5                      819
#define TRAINER_PABLO_2                     820
#define TRAINER_PABLO_3                     821
#define TRAINER_PABLO_4                     822
#define TRAINER_PABLO_5                     823
#define TRAINER_KOJI_2                      824
#define TRAINER_KOJI_3                      825
#define TRAINER_KOJI_4                      826
#define TRAINER_KOJI_5                      827
#define TRAINER_CRISTIN_2                   828
#define TRAINER_CRISTIN_3                   829
#define TRAINER_CRISTIN_4                   830
#define TRAINER_CRISTIN_5                   831
#define TRAINER_FERNANDO_2                  832
#define TRAINER_FERNANDO_3                  833
#define TRAINER_FERNANDO_4                  834
#define TRAINER_FERNANDO_5                  835
#define TRAINER_SAWYER_2                    836
#define TRAINER_SAWYER_3                    837
#define TRAINER_SAWYER_4                    838
#define TRAINER_SAWYER_5                    839
#define TRAINER_GABRIELLE_2                 840
#define TRAINER_GABRIELLE_3                 841
#define TRAINER_GABRIELLE_4                 842
#define TRAINER_GABRIELLE_5                 843
#define TRAINER_THALIA_2                    844
#define TRAINER_THALIA_3                    845
#define TRAINER_THALIA_4                    846
#define TRAINER_THALIA_5                    847
#define TRAINER_MARIELA                     848
#define TRAINER_ALVARO                      849
#define TRAINER_EVERETT                     850
#define TRAINER_RED                         851
#define TRAINER_LEAF                        852
#define TRAINER_BRENDAN_PLACEHOLDER         853
#define TRAINER_MAY_PLACEHOLDER             854

// FRLG trainers occupy IDs 900+frlgId (up to 900+624=1524) in the Emerald build.
// MAX_TRAINERS_COUNT must cover all IDs so trainer defeat flags allocate enough space.

#define TRAINERS_COUNT_EMERALD     1525
#define MAX_TRAINERS_COUNT_EMERALD 1668

#if IS_FRLG
#define TRAINERS_COUNT                      TRAINERS_COUNT_FRLG
#define MAX_TRAINERS_COUNT                  MAX_TRAINERS_COUNT_FRLG
#else
#define TRAINERS_COUNT                      TRAINERS_COUNT_EMERALD
#define MAX_TRAINERS_COUNT                  MAX_TRAINERS_COUNT_EMERALD
#endif
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H

// Johto trainer stubs (TODO: add trainer data from HnS)
#ifndef TRAINER_ABE
#define TRAINER_ABE  TRAINER_NONE
#endif
#ifndef TRAINER_AL
#define TRAINER_AL  TRAINER_NONE
#endif
#ifndef TRAINER_ALFRED
#define TRAINER_ALFRED  TRAINER_NONE
#endif
#ifndef TRAINER_AMY_AND_MAY
#define TRAINER_AMY_AND_MAY  TRAINER_NONE
#endif
#ifndef TRAINER_ANDRE
#define TRAINER_ANDRE  TRAINER_NONE
#endif
#ifndef TRAINER_ANN_AND_ANNE
#define TRAINER_ANN_AND_ANNE  TRAINER_NONE
#endif
#ifndef TRAINER_ARCHER
#define TRAINER_ARCHER  TRAINER_NONE
#endif
#ifndef TRAINER_ARIANA_2
#define TRAINER_ARIANA_2  TRAINER_NONE
#endif
#ifndef TRAINER_ARNIE
#define TRAINER_ARNIE  TRAINER_NONE
#endif
#ifndef TRAINER_BILL
#define TRAINER_BILL  TRAINER_NONE
#endif
#ifndef TRAINER_BRAD
#define TRAINER_BRAD  TRAINER_NONE
#endif
#ifndef TRAINER_BRIAN
#define TRAINER_BRIAN  TRAINER_NONE
#endif
#ifndef TRAINER_BROOKE
#define TRAINER_BROOKE  TRAINER_NONE
#endif
#ifndef TRAINER_BUGSY_1
#define TRAINER_BUGSY_1  TRAINER_NONE
#endif
#ifndef TRAINER_CALVIN
#define TRAINER_CALVIN  TRAINER_NONE
#endif
#ifndef TRAINER_CARA
#define TRAINER_CARA  TRAINER_NONE
#endif
#ifndef TRAINER_CARRIE
#define TRAINER_CARRIE  TRAINER_NONE
#endif
#ifndef TRAINER_CHOW
#define TRAINER_CHOW  TRAINER_NONE
#endif
#ifndef TRAINER_CHUCK_1
#define TRAINER_CHUCK_1  TRAINER_NONE
#endif
#ifndef TRAINER_CHUCK_1_2
#define TRAINER_CHUCK_1_2  TRAINER_NONE
#endif
#ifndef TRAINER_CHUCK_1_3
#define TRAINER_CHUCK_1_3  TRAINER_NONE
#endif
#ifndef TRAINER_CLAIR_1
#define TRAINER_CLAIR_1  TRAINER_NONE
#endif
#ifndef TRAINER_CODY
#define TRAINER_CODY  TRAINER_NONE
#endif
#ifndef TRAINER_DANIEL
#define TRAINER_DANIEL  TRAINER_NONE
#endif
#ifndef TRAINER_DARIN
#define TRAINER_DARIN  TRAINER_NONE
#endif
#ifndef TRAINER_DENIS
#define TRAINER_DENIS  TRAINER_NONE
#endif
#ifndef TRAINER_DIRK
#define TRAINER_DIRK  TRAINER_NONE
#endif
#ifndef TRAINER_DON
#define TRAINER_DON  TRAINER_NONE
#endif
#ifndef TRAINER_ELLIOT
#define TRAINER_ELLIOT  TRAINER_NONE
#endif
#ifndef TRAINER_EMMA
#define TRAINER_EMMA  TRAINER_NONE
#endif
#ifndef TRAINER_ERNEST
#define TRAINER_ERNEST  TRAINER_NONE
#endif
#ifndef TRAINER_ETO
#define TRAINER_ETO  TRAINER_NONE
#endif
#ifndef TRAINER_ETO_3
#define TRAINER_ETO_3  TRAINER_NONE
#endif
#ifndef TRAINER_EUGENE
#define TRAINER_EUGENE  TRAINER_NONE
#endif
#ifndef TRAINER_EUSINE
#define TRAINER_EUSINE  TRAINER_NONE
#endif
#ifndef TRAINER_FALKNER_1
#define TRAINER_FALKNER_1  TRAINER_NONE
#endif
#ifndef TRAINER_FRAN
#define TRAINER_FRAN  TRAINER_NONE
#endif
#ifndef TRAINER_GAVEN
#define TRAINER_GAVEN  TRAINER_NONE
#endif
#ifndef TRAINER_GINA
#define TRAINER_GINA  TRAINER_NONE
#endif
#ifndef TRAINER_GORDON
#define TRAINER_GORDON  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_10
#define TRAINER_GRUNT_10  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_11
#define TRAINER_GRUNT_11  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_12
#define TRAINER_GRUNT_12  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_19
#define TRAINER_GRUNT_19  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_2
#define TRAINER_GRUNT_2  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_20
#define TRAINER_GRUNT_20  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_21
#define TRAINER_GRUNT_21  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_22
#define TRAINER_GRUNT_22  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_26
#define TRAINER_GRUNT_26  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_27
#define TRAINER_GRUNT_27  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_28
#define TRAINER_GRUNT_28  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_3
#define TRAINER_GRUNT_3  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_33
#define TRAINER_GRUNT_33  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_4
#define TRAINER_GRUNT_4  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_5
#define TRAINER_GRUNT_5  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_6
#define TRAINER_GRUNT_6  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_7
#define TRAINER_GRUNT_7  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_8
#define TRAINER_GRUNT_8  TRAINER_NONE
#endif
#ifndef TRAINER_GRUNT_9
#define TRAINER_GRUNT_9  TRAINER_NONE
#endif
#ifndef TRAINER_HARRY
#define TRAINER_HARRY  TRAINER_NONE
#endif
#ifndef TRAINER_IAN
#define TRAINER_IAN  TRAINER_NONE
#endif
#ifndef TRAINER_IRWIN
#define TRAINER_IRWIN  TRAINER_NONE
#endif
#ifndef TRAINER_ISSAC
#define TRAINER_ISSAC  TRAINER_NONE
#endif
#ifndef TRAINER_JAKE
#define TRAINER_JAKE  TRAINER_NONE
#endif
#ifndef TRAINER_JAMIE
#define TRAINER_JAMIE  TRAINER_NONE
#endif
#ifndef TRAINER_JASMINE_1
#define TRAINER_JASMINE_1  TRAINER_NONE
#endif
#ifndef TRAINER_JASMINE_1_2
#define TRAINER_JASMINE_1_2  TRAINER_NONE
#endif
#ifndef TRAINER_JASMINE_1_3
#define TRAINER_JASMINE_1_3  TRAINER_NONE
#endif
#ifndef TRAINER_JEFFREY
#define TRAINER_JEFFREY  TRAINER_NONE
#endif
#ifndef TRAINER_JENN
#define TRAINER_JENN  TRAINER_NONE
#endif
#ifndef TRAINER_JIN
#define TRAINER_JIN  TRAINER_NONE
#endif
#ifndef TRAINER_JOYCE
#define TRAINER_JOYCE  TRAINER_NONE
#endif
#ifndef TRAINER_KATE
#define TRAINER_KATE  TRAINER_NONE
#endif
#ifndef TRAINER_KEITH
#define TRAINER_KEITH  TRAINER_NONE
#endif
#ifndef TRAINER_KIM
#define TRAINER_KIM  TRAINER_NONE
#endif
#ifndef TRAINER_KRISE
#define TRAINER_KRISE  TRAINER_NONE
#endif
#ifndef TRAINER_KUNI
#define TRAINER_KUNI  TRAINER_NONE
#endif
#ifndef TRAINER_LAO
#define TRAINER_LAO  TRAINER_NONE
#endif
#ifndef TRAINER_LEA_AND_PIA
#define TRAINER_LEA_AND_PIA  TRAINER_NONE
#endif
#ifndef TRAINER_LI
#define TRAINER_LI  TRAINER_NONE
#endif
#ifndef TRAINER_LIZ
#define TRAINER_LIZ  TRAINER_NONE
#endif
#ifndef TRAINER_LOIS
#define TRAINER_LOIS  TRAINER_NONE
#endif
#ifndef TRAINER_LOLA
#define TRAINER_LOLA  TRAINER_NONE
#endif
#ifndef TRAINER_MARKUS
#define TRAINER_MARKUS  TRAINER_NONE
#endif
#ifndef TRAINER_MEGAN
#define TRAINER_MEGAN  TRAINER_NONE
#endif
#ifndef TRAINER_MIKE
#define TRAINER_MIKE  TRAINER_NONE
#endif
#ifndef TRAINER_MIKEY
#define TRAINER_MIKEY  TRAINER_NONE
#endif
#ifndef TRAINER_MIKI
#define TRAINER_MIKI  TRAINER_NONE
#endif
#ifndef TRAINER_MILLER
#define TRAINER_MILLER  TRAINER_NONE
#endif
#ifndef TRAINER_MORTY_1
#define TRAINER_MORTY_1  TRAINER_NONE
#endif
#ifndef TRAINER_NAOKO
#define TRAINER_NAOKO  TRAINER_NONE
#endif
#ifndef TRAINER_NARD
#define TRAINER_NARD  TRAINER_NONE
#endif
#ifndef TRAINER_NATHAN
#define TRAINER_NATHAN  TRAINER_NONE
#endif
#ifndef TRAINER_NEAL
#define TRAINER_NEAL  TRAINER_NONE
#endif
#ifndef TRAINER_NICK
#define TRAINER_NICK  TRAINER_NONE
#endif
#ifndef TRAINER_NICO
#define TRAINER_NICO  TRAINER_NONE
#endif
#ifndef TRAINER_NOB
#define TRAINER_NOB  TRAINER_NONE
#endif
#ifndef TRAINER_NORMAN
#define TRAINER_NORMAN  TRAINER_NONE
#endif
#ifndef TRAINER_PETER
#define TRAINER_PETER  TRAINER_NONE
#endif
#ifndef TRAINER_PETREL_2
#define TRAINER_PETREL_2  TRAINER_NONE
#endif
#ifndef TRAINER_PING
#define TRAINER_PING  TRAINER_NONE
#endif
#ifndef TRAINER_PROTON_1
#define TRAINER_PROTON_1  TRAINER_NONE
#endif
#ifndef TRAINER_PROTON_2
#define TRAINER_PROTON_2  TRAINER_NONE
#endif
#ifndef TRAINER_PRYCE_1
#define TRAINER_PRYCE_1  TRAINER_NONE
#endif
#ifndef TRAINER_PRYCE_1_2
#define TRAINER_PRYCE_1_2  TRAINER_NONE
#endif
#ifndef TRAINER_PRYCE_1_3
#define TRAINER_PRYCE_1_3  TRAINER_NONE
#endif
#ifndef TRAINER_RALPH
#define TRAINER_RALPH  TRAINER_NONE
#endif
#ifndef TRAINER_RAY
#define TRAINER_RAY  TRAINER_NONE
#endif
#ifndef TRAINER_RAYMOND
#define TRAINER_RAYMOND  TRAINER_NONE
#endif
#ifndef TRAINER_RED_2
#define TRAINER_RED_2  TRAINER_NONE
#endif
#ifndef TRAINER_REENA
#define TRAINER_REENA  TRAINER_NONE
#endif
#ifndef TRAINER_RICH
#define TRAINER_RICH  TRAINER_NONE
#endif
#ifndef TRAINER_RICHARDO
#define TRAINER_RICHARDO  TRAINER_NONE
#endif
#ifndef TRAINER_RIVAL_CHIKORITA_1
#define TRAINER_RIVAL_CHIKORITA_1  TRAINER_NONE
#endif
#ifndef TRAINER_RIVAL_CHIKORITA_2
#define TRAINER_RIVAL_CHIKORITA_2  TRAINER_NONE
#endif
#ifndef TRAINER_RIVAL_CHIKORITA_3
#define TRAINER_RIVAL_CHIKORITA_3  TRAINER_NONE
#endif
#ifndef TRAINER_RIVAL_CHIKORITA_4
#define TRAINER_RIVAL_CHIKORITA_4  TRAINER_NONE
#endif
#ifndef TRAINER_RIVAL_CYNDAQUIL_1
#define TRAINER_RIVAL_CYNDAQUIL_1  TRAINER_NONE
#endif
#ifndef TRAINER_RIVAL_CYNDAQUIL_2
#define TRAINER_RIVAL_CYNDAQUIL_2  TRAINER_NONE
#endif
#ifndef TRAINER_RIVAL_CYNDAQUIL_3
#define TRAINER_RIVAL_CYNDAQUIL_3  TRAINER_NONE
#endif
#ifndef TRAINER_RIVAL_CYNDAQUIL_4
#define TRAINER_RIVAL_CYNDAQUIL_4  TRAINER_NONE
#endif
#ifndef TRAINER_RIVAL_OAKS_LAB_BULBASAUR
#define TRAINER_RIVAL_OAKS_LAB_BULBASAUR  TRAINER_NONE
#endif
#ifndef TRAINER_RIVAL_OAKS_LAB_CHARMANDER
#define TRAINER_RIVAL_OAKS_LAB_CHARMANDER  TRAINER_NONE
#endif
#ifndef TRAINER_RIVAL_OAKS_LAB_SQUIRTLE
#define TRAINER_RIVAL_OAKS_LAB_SQUIRTLE  TRAINER_NONE
#endif
#ifndef TRAINER_RIVAL_TOTODILE_1
#define TRAINER_RIVAL_TOTODILE_1  TRAINER_NONE
#endif
#ifndef TRAINER_RIVAL_TOTODILE_2
#define TRAINER_RIVAL_TOTODILE_2  TRAINER_NONE
#endif
#ifndef TRAINER_RIVAL_TOTODILE_3
#define TRAINER_RIVAL_TOTODILE_3  TRAINER_NONE
#endif
#ifndef TRAINER_RIVAL_TOTODILE_4
#define TRAINER_RIVAL_TOTODILE_4  TRAINER_NONE
#endif
#ifndef TRAINER_ROD
#define TRAINER_ROD  TRAINER_NONE
#endif
#ifndef TRAINER_ROXANNE
#define TRAINER_ROXANNE  TRAINER_NONE
#endif
#ifndef TRAINER_RUSSELL
#define TRAINER_RUSSELL  TRAINER_NONE
#endif
#ifndef TRAINER_RUTH
#define TRAINER_RUTH  TRAINER_NONE
#endif
#ifndef TRAINER_SAYO
#define TRAINER_SAYO  TRAINER_NONE
#endif
#ifndef TRAINER_SCHOOL_EARL
#define TRAINER_SCHOOL_EARL  TRAINER_NONE
#endif
#ifndef TRAINER_SCOTT
#define TRAINER_SCOTT  TRAINER_NONE
#endif
#ifndef TRAINER_TERRELL
#define TRAINER_TERRELL  TRAINER_NONE
#endif
#ifndef TRAINER_TERU
#define TRAINER_TERU  TRAINER_NONE
#endif
#ifndef TRAINER_THEO
#define TRAINER_THEO  TRAINER_NONE
#endif
#ifndef TRAINER_TOBY
#define TRAINER_TOBY  TRAINER_NONE
#endif
#ifndef TRAINER_TODD
#define TRAINER_TODD  TRAINER_NONE
#endif
#ifndef TRAINER_TROY
#define TRAINER_TROY  TRAINER_NONE
#endif
#ifndef TRAINER_VALERIE
#define TRAINER_VALERIE  TRAINER_NONE
#endif
#ifndef TRAINER_WALT
#define TRAINER_WALT  TRAINER_NONE
#endif
#ifndef TRAINER_WHITNEY_1
#define TRAINER_WHITNEY_1  TRAINER_NONE
#endif
#ifndef TRAINER_YOSHI
#define TRAINER_YOSHI  TRAINER_NONE
#endif
#ifndef TRAINER_ZUKI
#define TRAINER_ZUKI  TRAINER_NONE
#endif
